# 08K: Development foreground patch correspondence

This notebook tests one final 2D improvement to cross-view object identity. It keeps the existing LocateAnything, SAM 2.1, DINOv2-small and P1 pipeline fixed. It does not change the 2,000-scene experiment or use calibration or internal-lock data.

The comparison uses the sealed 100-scene development screen. The current global DINO matching is compared with reciprocal foreground patches, dustbin Sinkhorn patch transport, and an order-free track assembly using the same transport cost.

Notebook file: `08k-development-patch-correspondence.ipynb`.

## Saved-output evidence copy

This notebook records the completed run for repository review. Its code and markdown match the clean runnable notebook. Private scene visuals and identifier-bearing output were removed. Safe aggregate tables and charts were retained.

Run stage: `08K Kaggle Version 3`  
Clean notebook SHA-256: `4f6784d1c07b0a785c3e792d6bd075a202a9f584a5fc95c31a388309abf15b9a`  
Downloaded saved-output SHA-256: `de144b50a36f8d39cfacf811369f419fcdaa7750fed5d1205e53f1cf517153c8`

## Scientific boundary

DINO patch tokens are selected only where the automatic SAM mask covers at least half of a patch. Global and patch distances receive equal weight. Every candidate keeps the existing unmatched cost of 0.35. Sinkhorn uses an epsilon of 0.05, 30 iterations and an explicit dustbin state.

The primary measure is cross-view identity-link F1. Average precision, top-1 accuracy, recall at two, track purity, identity switches, linked coverage, singleton rate, runtime and memory are reported alongside it. The promotion rule rejects gains caused by track fragmentation. There is no arbitrary accuracy gate.

## Runtime and source discovery

In [1]:
from pathlib import Path, PurePosixPath
from zipfile import ZIP_DEFLATED, ZipFile
import json
import os
import shutil
import stat
import subprocess
import sys

INPUT_ROOT = Path('/kaggle/input')
WORKING_ROOT = Path('/kaggle/working')
PACKAGE_ROOT = Path('/tmp/identity-patch-packages')
PREDICTION_OUTPUT = WORKING_ROOT / 'identity-patch-predictions'
EVALUATION_OUTPUT = WORKING_ROOT / 'identity-patch-evaluation'
PYTHON = Path(sys.executable)
EXPECT_RECOVERY = False
os.environ['PYTHONDONTWRITEBYTECODE'] = '1'

mount_roots = []
for pattern in ('*', 'datasets/*/*', 'datasets/*/*/versions/*', 'notebooks/*/*', 'notebooks/*/*/versions/*'):
    mount_roots.extend(path.resolve() for path in INPUT_ROOT.glob(pattern) if path.is_dir())
mount_roots = sorted(set(mount_roots))
source_archives = sorted({
    path for mount in mount_roots
    for path in mount.rglob('identity-patch-association-source-*.zip')
    if path.is_file()
})
if len(source_archives) > 1:
    raise ValueError(f'Expected at most one patch-association source archive, found {len(source_archives)}')

if source_archives:
    extraction = WORKING_ROOT / 'identity-patch-source'
    temporary = extraction.with_name(extraction.name + '.incomplete')
    if extraction.exists() or temporary.exists():
        raise FileExistsError('Source extraction destination is not empty')
    temporary.mkdir(parents=True)
    with ZipFile(source_archives[0]) as handle:
        entries = handle.infolist()
        names = [entry.filename for entry in entries]
        if not entries or len(names) != len(set(names)) or handle.testzip() is not None:
            raise ValueError('Source archive is empty, duplicated or corrupt')
        for entry in entries:
            relative = PurePosixPath(entry.filename)
            mode = entry.external_attr >> 16
            if entry.is_dir() or relative.is_absolute() or any(part in ('', '.', '..') for part in relative.parts) or stat.S_ISLNK(mode):
                raise ValueError('Source archive contains an unsafe path')
            destination = temporary.joinpath(*relative.parts)
            destination.parent.mkdir(parents=True, exist_ok=True)
            with handle.open(entry) as source_stream, destination.open('xb') as target_stream:
                shutil.copyfileobj(source_stream, target_stream, length=1024 * 1024)
    temporary.replace(extraction)
    search_roots = [extraction]
    source_label = source_archives[0].name
else:
    search_roots = mount_roots
    source_label = 'expanded Kaggle dataset'

source_candidates = sorted({
    path.parents[3]
    for root in search_roots
    for path in root.rglob('patch_correspondence.py')
    if (path.parents[3] / 'scripts/run_identity_patch_association.py').is_file()
})
if len(source_candidates) != 1:
    raise ValueError(f'Expected one source root, found {len(source_candidates)}')
SOURCE = source_candidates[0]
sys.path.insert(0, str(SOURCE / 'scripts'))
from kaggle_mounts import find_prediction, find_recovery, materialize_sealed_resource
from scoring_comparison_runtime import run_bounded, tracking_credentials
print(json.dumps({'event': 'source_ready', 'source': source_label}, sort_keys=True))

{"event": "source_ready", "source": "expanded Kaggle dataset"}

## Method references

The reciprocal comparison follows the mutual-nearest-neighbour idea used by Best-Buddies Similarity. The transport comparison combines foreground-weighted semantic correspondence with the dustbin assignment pattern used for partial matching. DINOv2-small remains the frozen visual representation used by the current project.

- Dekel et al., *Best-Buddies Similarity for Robust Template Matching*, CVPR 2015.
- Liu et al., *Semantic Correspondence as an Optimal Transport Problem*, CVPR 2020.
- Sarlin et al., *SuperGlue: Learning Feature Matching with Graph Neural Networks*, CVPR 2020.
- Oquab et al., *DINOv2: Learning Robust Visual Features without Supervision*, 2023.

## Dependency and contract checks

The notebook keeps Kaggle's CUDA-compatible PyTorch build. It installs only pinned add-ons into a run-local folder, compiles the relevant modules and runs the focused unit and workflow-contract tests before loading the model.

In [2]:
PACKAGE_ROOT.mkdir(parents=True, exist_ok=True)
subprocess.run([
    str(PYTHON), '-m', 'pip', 'install', '--disable-pip-version-check',
    '--retries', '1', '--timeout', '60', '--only-binary=:all:',
    '--upgrade', '--target', str(PACKAGE_ROOT),
    '-r', str(SOURCE / 'requirements/identity-patch-association.txt'),
], check=True, timeout=600)
os.environ['PYTHONPATH'] = os.pathsep.join([
    str(SOURCE / 'src'), str(PACKAGE_ROOT), os.environ.get('PYTHONPATH', '')
]).rstrip(os.pathsep)
os.environ['MPLCONFIGDIR'] = str(WORKING_ROOT / 'matplotlib')
sys.path.insert(0, str(PACKAGE_ROOT))
RUNNER = SOURCE / 'scripts/run_identity_patch_association.py'
test_env = dict(os.environ, PYTHONDONTWRITEBYTECODE='1')
subprocess.run([
    str(PYTHON), '-m', 'pytest', '-p', 'no:cacheprovider', '-q',
    str(SOURCE / 'tests/test_patch_correspondence.py'),
    str(SOURCE / 'tests/test_identity_patch_association_contract.py'),
], check=True, cwd=WORKING_ROOT, env=test_env, timeout=300)
for source_file in (
    SOURCE / 'src/visual_peer_inspector/representation/patch_correspondence.py',
    SOURCE / 'src/visual_peer_inspector/workflows/identity_patch_association_study.py',
    RUNNER,
):
    compile(source_file.read_text(encoding='utf-8'), str(source_file), 'exec')

Collecting transformers==5.14.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading transformers-5.14.1-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub==1.26.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading huggingface_hub-1.26.1-py3-none-any.whl.metadata (16 kB)
Collecting numpy==2.5.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 4))
  Downloading numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pandas==2.3.3 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 5))
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 2.6 MB/s eta 0:00:00
Collecting pillow==12.3.0 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 6))
  Downloading pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting scipy==1.16.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 7))
  Downloading scipy-1.16.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.2 MB/s eta 0:00:00
Collecting matplotlib==3.10.8 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 8))
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 2.8 MB/s eta 0:00:00
Collecting nbformat==5.11.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading nbformat-5.11.1-py3-none-any.whl.metadata (3.7 kB)
Collecting pytest==9.1.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 10))
  Downloading pytest-9.1.1-py3-none-any.whl.metadata (7.6 kB)
Collecting packaging>=20.0 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml>=5.1 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting regex>=2025.10.22 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading regex-2026.9.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 1.3 MB/s eta 0:00:00
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading typer-0.27.2-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.8.0 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting tqdm>=4.60 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.4/57.4 kB 3.0 MB/s eta 0:00:00
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock>=3.10.0 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading filelock-3.32.6-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting python-dateutil>=2.8.2 (from pandas==2.3.3->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 5))
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.3.3->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 5))
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.3.3->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 5))
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 8))
  Downloading contourpy-1.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 8))
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 8))
  Downloading fonttools-4.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 5.8 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 8))
  Downloading kiwisolver-1.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.2 kB)
Collecting pyparsing>=3 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 8))
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting fastjsonschema>=2.15 (from nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading fastjsonschema-2.22.2-py3-none-any.whl.metadata (2.1 kB)
Collecting jsonschema>=2.6 (from nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading jupyter_core-5.9.1-py3-none-any.whl.metadata (1.5 kB)
Collecting traitlets>=5.1 (from nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading traitlets-5.16.1-py3-none-any.whl.metadata (10 kB)
Collecting iniconfig>=1.0.1 (from pytest==9.1.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 10))
  Downloading iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting pluggy<2,>=1.5 (from pytest==9.1.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 10))
  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Collecting pygments>=2.7.2 (from pytest==9.1.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 10))
  Downloading pygments-2.21.0-py3-none-any.whl.metadata (2.5 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi (from httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 3))
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting platformdirs>=2.5 (from jupyter-core!=5.0.*,>=4.12->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 9))
  Downloading platformdirs-4.11.8-py3-none-any.whl.metadata (5.5 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.3.3->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 5))
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting shellingham>=1.3.0 (from typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-patch-association-source/identity-patch-association/requirements/identity-patch-association.txt (line 2))
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading transformers-5.14.1-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 84.5 MB/s eta 0:00:00
Downloading huggingface_hub-1.26.1-py3-none-any.whl (780 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.8/780.8 kB 25.4 MB/s eta 0:00:00
Downloading numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 82.4 MB/s eta 0:00:00
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 101.1 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 102.3 MB/s eta 0:00:00
Downloading scipy-1.16.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (35.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 58.0 MB/s eta 0:00:00
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 107.5 MB/s eta 0:00:00
Downloading nbformat-5.11.1-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 4.8 MB/s eta 0:00:00
Downloading pytest-9.1.1-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.5/386.5 kB 22.8 MB/s eta 0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.3/125.3 kB 6.1 MB/s eta 0:00:00
Downloading contourpy-1.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.2/383.2 kB 21.3 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fastjsonschema-2.22.2-py3-none-any.whl (27 kB)
Downloading filelock-3.32.6-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.2/100.2 kB 5.2 MB/s eta 0:00:00
Downloading fonttools-4.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 85.0 MB/s eta 0:00:00
Downloading fsspec-2026.7.0-py3-none-any.whl (206 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.6/206.6 kB 10.1 MB/s eta 0:00:00
Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 89.4 MB/s eta 0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 5.1 MB/s eta 0:00:00
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 5.4 MB/s eta 0:00:00
Downloading iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 4.5 MB/s eta 0:00:00
Downloading jupyter_core-5.9.1-py3-none-any.whl (29 kB)
Downloading kiwisolver-1.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 59.2 MB/s eta 0:00:00
Downloading packaging-26.3-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 8.1 MB/s eta 0:00:00
Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)
Downloading pygments-2.21.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 45.3 MB/s eta 0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.8/122.8 kB 8.1 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 11.3 MB/s eta 0:00:00
Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.3/508.3 kB 27.0 MB/s eta 0:00:00
Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
datasets 5.0.0 requires fsspec[http]<=2026.4.0,>=2023.1.0, but you have fsspec 2026.7.0 which is incompatible.
ydata-profiling 4.18.4 requires matplotlib<=3.10,>=3.5, but you have matplotlib 3.10.8 which is incompatible.
ydata-profiling 4.18.4 requires numpy<2.4,>=1.22, but you have numpy 2.5.1 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.
bigframes 2.39.0 requires rich<14,>=12.4.4, but you have rich 15.0.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.1 which is incompatible.
pyiceberg 0.11.1 requires rich<15.0.0,>=10.11.0, but you have rich 15.0.0 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.7.0 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.3.0 which is incompatible.

Successfully installed annotated-doc-0.0.5 anyio-4.15.1 attrs-26.1.0 certifi-2026.7.22 click-8.5.0 contourpy-1.4.0 cycler-0.12.1 fastjsonschema-2.22.2 filelock-3.32.6 fonttools-4.65.0 fsspec-2026.7.0 h11-0.16.0 hf-xet-1.6.0 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.26.1 idna-3.19 iniconfig-2.3.0 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 jupyter-core-5.9.1 kiwisolver-1.5.1 markdown-it-py-4.2.0 matplotlib-3.10.8 mdurl-0.1.2 nbformat-5.11.1 numpy-2.5.1 packaging-26.3 pandas-2.3.3 pillow-12.3.0 platformdirs-4.11.8 pluggy-1.6.0 pygments-2.21.0 pyparsing-3.3.2 pytest-9.1.1 python-dateutil-2.9.0.post0 pytz-2026.3.post1 pyyaml-6.0.3 referencing-0.37.0 regex-2026.9.10 rich-15.0.0 rpds-py-2026.6.3 safetensors-0.8.0 scipy-1.16.1 shellingham-1.5.4 six-1.17.0 tokenizers-0.22.2 tqdm-4.70.1 traitlets-5.16.1 transformers-5.14.1 typer-0.27.2 typing-extensions-4.16.0 tzdata-2026.4
.............                                                            [100%]
13 passed in 2.05s

## Locked development inputs

In [3]:
MODEL_INPUT = materialize_sealed_resource(
    INPUT_ROOT,
    kind='model-input',
    archive_name='scoring-comparison-model-input.zip',
    archive_sha256='6d6b45aa211ea595524729123870307ee5295ada48e6fd8f1898935f477b6901',
    destination=WORKING_ROOT / 'identity-patch-model-resource',
    expected_lock_sha256='9baa53454d2482caf8240e7a8b591a6e9e9646dd160c5b3abdc8bd17265ebda1',
)
from hashlib import sha256
model_lock_sha256 = sha256((MODEL_INPUT / 'artifact_lock.json').read_bytes()).hexdigest()
SCORING = find_prediction(INPUT_ROOT, expected_input_lock_sha256=model_lock_sha256)
if not (SCORING / 'feature_lock.json').is_file():
    raise FileNotFoundError('Attach the completed 08G output with its feature lock')
run_bounded([
    str(PYTHON), str(RUNNER), 'preflight',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--output', str(PREDICTION_OUTPUT),
], WORKING_ROOT / 'identity-patch-preflight.log', idle_seconds=300, total_seconds=900)

{'scene_count': 100, 'scenes': ['[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]'], 'view_count': 8, 'configuration_count_per_scene': 12, 'model_input_lock_sha256': '9baa53454d2482caf8240e7a8b591a6e9e9646dd160c5b3abdc8bd17265ebda1', 'scoring_prediction_lock_sha256': '12ce9bfc2bb401c29621d91000c53ff4fd39504fc28e55ff8a921e0b5443690d'}

## Checked recovery plan

Every completed scene is written atomically with a checksum receipt. Recovery is accepted only when the source, inputs, dependencies and protocol match exactly. A fresh run ignores unrelated recovery files mounted by Kaggle.

In [4]:
RECOVERY = find_recovery(INPUT_ROOT) if EXPECT_RECOVERY else None
if EXPECT_RECOVERY and RECOVERY is None:
    raise FileNotFoundError('This continuation requires one verified recovery archive and manifest')
recovery_arguments = [] if RECOVERY is None else [
    '--recovery-bundle', str(RECOVERY[0]),
    '--recovery-manifest', str(RECOVERY[1]),
]
print(json.dumps({
    'event': 'recovery_plan',
    'expected': EXPECT_RECOVERY,
    'attached': RECOVERY is not None,
}, sort_keys=True))

{"attached": false, "event": "recovery_plan", "expected": false}

## Lock label-free identity predictions

One GPU extracts DINOv2-small patch tokens from the eight fixed views. The existing global embeddings and anomaly scores are reused. A 15-minute silent limit stops a stalled process and a four-hour total limit protects GPU time. Completed scene checkpoints remain reusable after an operational interruption.

In [5]:
run_bounded([
    str(PYTHON), str(RUNNER), 'predict',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--output', str(PREDICTION_OUTPUT), *recovery_arguments,
], WORKING_ROOT / 'identity-patch-prediction.log', idle_seconds=900, total_seconds=14400)
run_bounded([
    str(PYTHON), str(RUNNER), 'verify',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--output', str(PREDICTION_OUTPUT),
], WORKING_ROOT / 'identity-patch-prediction-verification.log', idle_seconds=300, total_seconds=600)
display(json.loads((PREDICTION_OUTPUT / 'run_status.json').read_text()))
display(json.loads((PREDICTION_OUTPUT / 'progress.json').read_text()))

{'event': 'runtime_ready', 'gpu': 'Tesla T4', 'visible_gpus': 2, 'devices_used': 1, 'output_free_bytes': 20940447744}
{"event": "model_load_start", "revision": "ed25f3a31f01632728cabb09d1542f84ab7b0056"}
{'event': 'model_download_start', 'revision': 'ed25f3a31f01632728cabb09d1542f84ab7b0056'}

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Fetching 6 files:  17%|█▋        | 1/6 [00:00<00:00,  5.66it/s]
Fetching 6 files:  83%|████████▎ | 5/6 [00:01<00:00,  3.41it/s]
Fetching 6 files: 100%|██████████| 6/6 [00:06<00:00,  1.48s/it]
Fetching 6 files: 100%|██████████| 6/6 [00:06<00:00,  1.13s/it]
{'event': 'model_download_complete', 'snapshot': 'ed25f3a31f01632728cabb09d1542f84ab7b0056'}

Loading weights:   0%|          | 0/223 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 223/223 [00:00<00:00, 2493.50it/s]
{'event': 'model_cpu_ready'}
{'event': 'model_cuda_ready', 'allocated_bytes': 88226304}
{"event": "model_ready"}
{"event": "scene_complete", "scene_number": 1, "total": 100}
{"event": "scene_complete", "scene_number": 2, "total": 100}
{"event": "scene_complete", "scene_number": 3, "total": 100}
{"event": "scene_complete", "scene_number": 4, "total": 100}
{"event": "scene_complete", "scene_number": 5, "total": 100}
{"event": "scene_complete", "scene_number": 6, "total": 100}
{"event": "scene_complete", "scene_number": 7, "total": 100}
{"event": "scene_complete", "scene_number": 8, "total": 100}
{"event": "scene_complete", "scene_number": 9, "total": 100}
{"event": "scene_complete", "scene_number": 10, "total": 100}
{"event": "scene_complete", "scene_number": 11, "total": 100}
{"event": "scene_complete", "scene_number": 12, "total": 100}
{"event": "scene_complete", "scene_number": 13, "total": 100}
{"event": "scene_complete", "scene_number": 14, "total": 100}
{"event": "scene_complete", "scene_number": 15, "total": 100}
{"event": "scene_complete", "scene_number": 16, "total": 100}
{"event": "scene_complete", "scene_number": 17, "total": 100}
{"event": "scene_complete", "scene_number": 18, "total": 100}
{"event": "scene_complete", "scene_number": 19, "total": 100}
{"event": "scene_complete", "scene_number": 20, "total": 100}
{"event": "scene_complete", "scene_number": 21, "total": 100}
{"event": "scene_complete", "scene_number": 22, "total": 100}
{"event": "scene_complete", "scene_number": 23, "total": 100}
{"event": "scene_complete", "scene_number": 24, "total": 100}
{"event": "scene_complete", "scene_number": 25, "total": 100}
{"event": "scene_complete", "scene_number": 26, "total": 100}
{"event": "scene_complete", "scene_number": 27, "total": 100}
{"event": "scene_complete", "scene_number": 28, "total": 100}
{"event": "scene_complete", "scene_number": 29, "total": 100}
{"event": "scene_complete", "scene_number": 30, "total": 100}
{"event": "scene_complete", "scene_number": 31, "total": 100}
{"event": "scene_complete", "scene_number": 32, "total": 100}
{"event": "scene_complete", "scene_number": 33, "total": 100}
{"event": "scene_complete", "scene_number": 34, "total": 100}
{"event": "scene_complete", "scene_number": 35, "total": 100}
{"event": "scene_complete", "scene_number": 36, "total": 100}
{"event": "scene_complete", "scene_number": 37, "total": 100}
{"event": "scene_complete", "scene_number": 38, "total": 100}
{"event": "scene_complete", "scene_number": 39, "total": 100}
{"event": "scene_complete", "scene_number": 40, "total": 100}
{"event": "scene_complete", "scene_number": 41, "total": 100}
{"event": "scene_complete", "scene_number": 42, "total": 100}
{"event": "scene_complete", "scene_number": 43, "total": 100}
{"event": "scene_complete", "scene_number": 44, "total": 100}
{"event": "scene_complete", "scene_number": 45, "total": 100}
{"event": "scene_complete", "scene_number": 46, "total": 100}
{"event": "scene_complete", "scene_number": 47, "total": 100}
{"event": "scene_complete", "scene_number": 48, "total": 100}
{"event": "scene_complete", "scene_number": 49, "total": 100}
{"event": "scene_complete", "scene_number": 50, "total": 100}
{"event": "scene_complete", "scene_number": 51, "total": 100}
{"event": "scene_complete", "scene_number": 52, "total": 100}
{"event": "scene_complete", "scene_number": 53, "total": 100}
{"event": "scene_complete", "scene_number": 54, "total": 100}
{"event": "scene_complete", "scene_number": 55, "total": 100}
{"event": "scene_complete", "scene_number": 56, "total": 100}
{"event": "scene_complete", "scene_number": 57, "total": 100}
{"event": "scene_complete", "scene_number": 58, "total": 100}
{"event": "scene_complete", "scene_number": 59, "total": 100}
{"event": "scene_complete", "scene_number": 60, "total": 100}
{"event": "scene_complete", "scene_number": 61, "total": 100}
{"event": "scene_complete", "scene_number": 62, "total": 100}
{"event": "scene_complete", "scene_number": 63, "total": 100}
{"event": "scene_complete", "scene_number": 64, "total": 100}
{"event": "scene_complete", "scene_number": 65, "total": 100}
{"event": "scene_complete", "scene_number": 66, "total": 100}
{"event": "scene_complete", "scene_number": 67, "total": 100}
{"event": "scene_complete", "scene_number": 68, "total": 100}
{"event": "scene_complete", "scene_number": 69, "total": 100}
{"event": "scene_complete", "scene_number": 70, "total": 100}
{"event": "scene_complete", "scene_number": 71, "total": 100}
{"event": "scene_complete", "scene_number": 72, "total": 100}
{"event": "scene_complete", "scene_number": 73, "total": 100}
{"event": "scene_complete", "scene_number": 74, "total": 100}
{"event": "scene_complete", "scene_number": 75, "total": 100}
{"event": "scene_complete", "scene_number": 76, "total": 100}
{"event": "scene_complete", "scene_number": 77, "total": 100}
{"event": "scene_complete", "scene_number": 78, "total": 100}
{"event": "scene_complete", "scene_number": 79, "total": 100}
{"event": "scene_complete", "scene_number": 80, "total": 100}
{"event": "scene_complete", "scene_number": 81, "total": 100}
{"event": "scene_complete", "scene_number": 82, "total": 100}
{"event": "scene_complete", "scene_number": 83, "total": 100}
{"event": "scene_complete", "scene_number": 84, "total": 100}
{"event": "scene_complete", "scene_number": 85, "total": 100}
{"event": "scene_complete", "scene_number": 86, "total": 100}
{"event": "scene_complete", "scene_number": 87, "total": 100}
{"event": "scene_complete", "scene_number": 88, "total": 100}
{"event": "scene_complete", "scene_number": 89, "total": 100}
{"event": "scene_complete", "scene_number": 90, "total": 100}
{"event": "scene_complete", "scene_number": 91, "total": 100}
{"event": "scene_complete", "scene_number": 92, "total": 100}
{"event": "scene_complete", "scene_number": 93, "total": 100}
{"event": "scene_complete", "scene_number": 94, "total": 100}
{"event": "scene_complete", "scene_number": 95, "total": 100}
{"event": "scene_complete", "scene_number": 96, "total": 100}
{"event": "scene_complete", "scene_number": 97, "total": 100}
{"event": "scene_complete", "scene_number": 98, "total": 100}
{"event": "scene_complete", "scene_number": 99, "total": 100}
{"event": "scene_complete", "scene_number": 100, "total": 100}
{'event': 'gpu_summary', 'peak_allocated_bytes': 163530240}

{'scene_count': 100, 'status': 'complete'}

{'complete_scenes': 100, 'expected_scenes': 100}

## Development-only evaluation

The evaluator package is opened only after the prediction lock exists and verifies. It measures identity quality and odd-one-out ranking without changing any prediction.

In [6]:
EVALUATOR = materialize_sealed_resource(
    INPUT_ROOT,
    kind='evaluator-only',
    archive_name='scoring-comparison-evaluator-only.zip',
    archive_sha256='86ac512005af5fdceb64c0fb666998832b8ee08ef96d1fccca23c6e35f420c12',
    destination=WORKING_ROOT / 'identity-patch-evaluator-resource',
    expected_lock_sha256='8012cd20c63b3788f861f2ba991b3181a0c1666f26e176beeee370228c8500c3',
)
run_bounded([
    str(PYTHON), str(RUNNER), 'evaluate',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--predictions', str(PREDICTION_OUTPUT), '--evaluator', str(EVALUATOR),
    '--output', str(EVALUATION_OUTPUT),
], WORKING_ROOT / 'identity-patch-evaluation.log', idle_seconds=900, total_seconds=7200)
run_bounded([
    str(PYTHON), str(RUNNER), 'verify',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--output', str(EVALUATION_OUTPUT),
], WORKING_ROOT / 'identity-patch-evaluation-verification.log', idle_seconds=300, total_seconds=600)

{"event": "scene_evaluated", "scene_number": 1, "total": 100}
{"event": "scene_evaluated", "scene_number": 2, "total": 100}
{"event": "scene_evaluated", "scene_number": 3, "total": 100}
{"event": "scene_evaluated", "scene_number": 4, "total": 100}
{"event": "scene_evaluated", "scene_number": 5, "total": 100}
{"event": "scene_evaluated", "scene_number": 6, "total": 100}
{"event": "scene_evaluated", "scene_number": 7, "total": 100}
{"event": "scene_evaluated", "scene_number": 8, "total": 100}
{"event": "scene_evaluated", "scene_number": 9, "total": 100}
{"event": "scene_evaluated", "scene_number": 10, "total": 100}
{"event": "scene_evaluated", "scene_number": 11, "total": 100}
{"event": "scene_evaluated", "scene_number": 12, "total": 100}
{"event": "scene_evaluated", "scene_number": 13, "total": 100}
{"event": "scene_evaluated", "scene_number": 14, "total": 100}
{"event": "scene_evaluated", "scene_number": 15, "total": 100}
{"event": "scene_evaluated", "scene_number": 16, "total": 100}
{"event": "scene_evaluated", "scene_number": 17, "total": 100}
{"event": "scene_evaluated", "scene_number": 18, "total": 100}
{"event": "scene_evaluated", "scene_number": 19, "total": 100}
{"event": "scene_evaluated", "scene_number": 20, "total": 100}
{"event": "scene_evaluated", "scene_number": 21, "total": 100}
{"event": "scene_evaluated", "scene_number": 22, "total": 100}
{"event": "scene_evaluated", "scene_number": 23, "total": 100}
{"event": "scene_evaluated", "scene_number": 24, "total": 100}
{"event": "scene_evaluated", "scene_number": 25, "total": 100}
{"event": "scene_evaluated", "scene_number": 26, "total": 100}
{"event": "scene_evaluated", "scene_number": 27, "total": 100}
{"event": "scene_evaluated", "scene_number": 28, "total": 100}
{"event": "scene_evaluated", "scene_number": 29, "total": 100}
{"event": "scene_evaluated", "scene_number": 30, "total": 100}
{"event": "scene_evaluated", "scene_number": 31, "total": 100}
{"event": "scene_evaluated", "scene_number": 32, "total": 100}
{"event": "scene_evaluated", "scene_number": 33, "total": 100}
{"event": "scene_evaluated", "scene_number": 34, "total": 100}
{"event": "scene_evaluated", "scene_number": 35, "total": 100}
{"event": "scene_evaluated", "scene_number": 36, "total": 100}
{"event": "scene_evaluated", "scene_number": 37, "total": 100}
{"event": "scene_evaluated", "scene_number": 38, "total": 100}
{"event": "scene_evaluated", "scene_number": 39, "total": 100}
{"event": "scene_evaluated", "scene_number": 40, "total": 100}
{"event": "scene_evaluated", "scene_number": 41, "total": 100}
{"event": "scene_evaluated", "scene_number": 42, "total": 100}
{"event": "scene_evaluated", "scene_number": 43, "total": 100}
{"event": "scene_evaluated", "scene_number": 44, "total": 100}
{"event": "scene_evaluated", "scene_number": 45, "total": 100}
{"event": "scene_evaluated", "scene_number": 46, "total": 100}
{"event": "scene_evaluated", "scene_number": 47, "total": 100}
{"event": "scene_evaluated", "scene_number": 48, "total": 100}
{"event": "scene_evaluated", "scene_number": 49, "total": 100}
{"event": "scene_evaluated", "scene_number": 50, "total": 100}
{"event": "scene_evaluated", "scene_number": 51, "total": 100}
{"event": "scene_evaluated", "scene_number": 52, "total": 100}
{"event": "scene_evaluated", "scene_number": 53, "total": 100}
{"event": "scene_evaluated", "scene_number": 54, "total": 100}
{"event": "scene_evaluated", "scene_number": 55, "total": 100}
{"event": "scene_evaluated", "scene_number": 56, "total": 100}
{"event": "scene_evaluated", "scene_number": 57, "total": 100}
{"event": "scene_evaluated", "scene_number": 58, "total": 100}
{"event": "scene_evaluated", "scene_number": 59, "total": 100}
{"event": "scene_evaluated", "scene_number": 60, "total": 100}
{"event": "scene_evaluated", "scene_number": 61, "total": 100}
{"event": "scene_evaluated", "scene_number": 62, "total": 100}
{"event": "scene_evaluated", "scene_number": 63, "total": 100}
{"event": "scene_evaluated", "scene_number": 64, "total": 100}
{"event": "scene_evaluated", "scene_number": 65, "total": 100}
{"event": "scene_evaluated", "scene_number": 66, "total": 100}
{"event": "scene_evaluated", "scene_number": 67, "total": 100}
{"event": "scene_evaluated", "scene_number": 68, "total": 100}
{"event": "scene_evaluated", "scene_number": 69, "total": 100}
{"event": "scene_evaluated", "scene_number": 70, "total": 100}
{"event": "scene_evaluated", "scene_number": 71, "total": 100}
{"event": "scene_evaluated", "scene_number": 72, "total": 100}
{"event": "scene_evaluated", "scene_number": 73, "total": 100}
{"event": "scene_evaluated", "scene_number": 74, "total": 100}
{"event": "scene_evaluated", "scene_number": 75, "total": 100}
{"event": "scene_evaluated", "scene_number": 76, "total": 100}
{"event": "scene_evaluated", "scene_number": 77, "total": 100}
{"event": "scene_evaluated", "scene_number": 78, "total": 100}
{"event": "scene_evaluated", "scene_number": 79, "total": 100}
{"event": "scene_evaluated", "scene_number": 80, "total": 100}
{"event": "scene_evaluated", "scene_number": 81, "total": 100}
{"event": "scene_evaluated", "scene_number": 82, "total": 100}
{"event": "scene_evaluated", "scene_number": 83, "total": 100}
{"event": "scene_evaluated", "scene_number": 84, "total": 100}
{"event": "scene_evaluated", "scene_number": 85, "total": 100}
{"event": "scene_evaluated", "scene_number": 86, "total": 100}
{"event": "scene_evaluated", "scene_number": 87, "total": 100}
{"event": "scene_evaluated", "scene_number": 88, "total": 100}
{"event": "scene_evaluated", "scene_number": 89, "total": 100}
{"event": "scene_evaluated", "scene_number": 90, "total": 100}
{"event": "scene_evaluated", "scene_number": 91, "total": 100}
{"event": "scene_evaluated", "scene_number": 92, "total": 100}
{"event": "scene_evaluated", "scene_number": 93, "total": 100}
{"event": "scene_evaluated", "scene_number": 94, "total": 100}
{"event": "scene_evaluated", "scene_number": 95, "total": 100}
{"event": "scene_evaluated", "scene_number": 96, "total": 100}
{"event": "scene_evaluated", "scene_number": 97, "total": 100}
{"event": "scene_evaluated", "scene_number": 98, "total": 100}
{"event": "scene_evaluated", "scene_number": 99, "total": 100}
{"event": "scene_evaluated", "scene_number": 100, "total": 100}
        configuration_id                          family  view_count           method  scenes  asset_groups       ap  top1  recall_at_2    auroc  identity_link_precision  identity_link_recall  identity_link_f1  identity_track_purity  identity_switch_rate  track_completeness  linked_node_fraction  singleton_fraction  mean_track_support  mean_edge_margin  mean_patch_match_fraction  mean_patch_entropy  winner_support  winner_purity
   current_hungarian_035                 global_baseline           2       P1_current     100            27 0.324845  0.24        0.300 0.319875                 0.154667              0.136500          0.142444               0.740000              0.790333            0.517083              0.806968            0.257424            1.722576               NaN                        NaN                 NaN            1.56       0.650000
   current_hungarian_035                 global_baseline           2     P2_consensus     100            27 0.316679  0.22        0.310 0.308625                 0.154667              0.136500          0.142444               0.740000              0.790333            0.517083              0.806968            0.257424            1.722576               NaN                        NaN                 NaN            1.64       0.590000
   current_hungarian_035                 global_baseline           2 forward_02_cov70     100            27 0.335833  0.27        0.325 0.323417                 0.154667              0.136500          0.142444               0.740000              0.790333            0.517083              0.806968            0.257424            1.722576               NaN                        NaN                 NaN            1.59       0.610000
   current_hungarian_035                 global_baseline           3       P1_current     100            27 0.319980  0.23        0.295 0.305462                 0.212644              0.173899          0.188789               0.687222              0.903500            0.735278              0.868418            0.231661            2.376201               NaN                        NaN                 NaN            2.15       0.476667
   current_hungarian_035                 global_baseline           3     P2_consensus     100            27 0.316694  0.21        0.290 0.313333                 0.212644              0.173899          0.188789               0.687222              0.903500            0.735278              0.868418            0.231661            2.376201               NaN                        NaN                 NaN            2.15       0.455000
   current_hungarian_035                 global_baseline           3 forward_02_cov70     100            27 0.339835  0.24        0.355 0.335573                 0.212644              0.173899          0.188789               0.687222              0.903500            0.735278              0.868418            0.231661            2.376201               NaN                        NaN                 NaN            2.10       0.426667
   current_hungarian_035                 global_baseline           5       P1_current     100            27 0.275236  0.19        0.295 0.301190                 0.257156              0.216434          0.232629               0.555000              0.951667            0.664667              0.930616            0.179067            3.721607               NaN                        NaN                 NaN            2.88       0.301833
   current_hungarian_035                 global_baseline           5     P2_consensus     100            27 0.254242  0.15        0.270 0.274824                 0.257156              0.216434          0.232629               0.555000              0.951667            0.664667              0.930616            0.179067            3.721607               NaN                        NaN                 NaN            2.94       0.299833
   current_hungarian_035                 global_baseline           5 forward_02_cov70     100            27 0.265845  0.17        0.280 0.299342                 0.257156              0.216434          0.232629               0.555000              0.951667            0.664667              0.930616            0.179067            3.721607               NaN                        NaN                 NaN            3.10       0.313333
reciprocal_hungarian_035 foreground_patch_correspondence           2       P1_current     100            27 0.344512  0.26        0.320 0.348333                 0.115000              0.091500          0.100556               0.820000              0.801667            0.511667              0.692000            0.393400            1.586600          0.029845                   0.350988            0.000000            1.42       0.655000
reciprocal_hungarian_035 foreground_patch_correspondence           2     P2_consensus     100            27 0.344036  0.26        0.335 0.332470                 0.115000              0.091500          0.100556               0.820000              0.801667            0.511667              0.692000            0.393400            1.586600          0.029845                   0.350988            0.000000            1.49       0.645000
reciprocal_hungarian_035 foreground_patch_correspondence           2 forward_02_cov70     100            27 0.356345  0.29        0.350 0.339577                 0.115000              0.091500          0.100556               0.820000              0.801667            0.511667              0.692000            0.393400            1.586600          0.029845                   0.350988            0.000000            1.47       0.630000
reciprocal_hungarian_035 foreground_patch_correspondence           3       P1_current     100            27 0.292294  0.22        0.250 0.302475                 0.187124              0.129274          0.149330               0.743611              0.900000            0.627222              0.750045            0.397817            2.034329          0.036735                   0.378121            0.000000            1.72       0.480000
reciprocal_hungarian_035 foreground_patch_correspondence           3     P2_consensus     100            27 0.279982  0.18        0.255 0.305769                 0.187124              0.129274          0.149330               0.743611              0.900000            0.627222              0.750045            0.397817            2.034329          0.036735                   0.378121            0.000000            1.74       0.420000
reciprocal_hungarian_035 foreground_patch_correspondence           3 forward_02_cov70     100            27 0.320992  0.25        0.325 0.334086                 0.187124              0.129274          0.149330               0.743611              0.900000            0.627222              0.750045            0.397817            2.034329          0.036735                   0.378121            0.000000            1.68       0.446667
reciprocal_hungarian_035 foreground_patch_correspondence           5       P1_current     100            27 0.244216  0.19        0.230 0.297181                 0.238359              0.165891          0.188843               0.625028              0.949167            0.582667              0.783941            0.434048            2.885546          0.030806                   0.376166            0.000000            2.19       0.264333
reciprocal_hungarian_035 foreground_patch_correspondence           5     P2_consensus     100            27 0.222817  0.14        0.210 0.273438                 0.238359              0.165891          0.188843               0.625028              0.949167            0.582667              0.783941            0.434048            2.885546          0.030806                   0.376166            0.000000            2.19       0.247000
reciprocal_hungarian_035 foreground_patch_correspondence           5 forward_02_cov70     100            27 0.254603  0.20        0.255 0.304517                 0.238359              0.165891          0.188843               0.625028              0.949167            0.582667              0.783941            0.434048            2.885546          0.030806                   0.376166            0.000000            2.32       0.275333
  sinkhorn_consensus_035 foreground_patch_correspondence           2       P1_current     100            27 0.358976  0.26        0.325 0.366125                 0.135500              0.112167          0.119508               0.770000              0.791167            0.498750              0.738024            0.337996            1.642004          0.025495                   0.843077            0.784107            1.49       0.670000
  sinkhorn_consensus_035 foreground_patch_correspondence           2     P2_consensus     100            27 0.358357  0.26        0.345 0.352125                 0.135500              0.112167          0.119508               0.770000              0.791167            0.498750              0.738024            0.337996            1.642004          0.025495                   0.843077            0.784107            1.56       0.630000
  sinkhorn_consensus_035 foreground_patch_correspondence           2 forward_02_cov70     100            27 0.383512  0.31        0.385 0.371542                 0.135500              0.112167          0.119508               0.770000              0.791167            0.498750              0.738024            0.337996            1.642004          0.025495                   0.843077            0.784107            1.52       0.635000
  sinkhorn_consensus_035 foreground_patch_correspondence           3       P1_current     100            27 0.290312  0.20        0.260 0.293360                 0.187141              0.138540          0.156375               0.725556              0.924167            0.675556              0.816625            0.306274            2.166810          0.032582                   0.890639            0.825871            1.88       0.448333
  sinkhorn_consensus_035 foreground_patch_correspondence           3     P2_consensus     100            27 0.301413  0.20        0.270 0.308339                 0.187141              0.138540          0.156375               0.725556              0.924167            0.675556              0.816625            0.306274            2.166810          0.032582                   0.890639            0.825871            1.87       0.423333
  sinkhorn_consensus_035 foreground_patch_correspondence           3 forward_02_cov70     100            27 0.353337  0.28        0.355 0.362470                 0.187141              0.138540          0.156375               0.725556              0.924167            0.675556              0.816625            0.306274            2.166810          0.032582                   0.890639            0.825871            1.88       0.441667
  sinkhorn_consensus_035 foreground_patch_correspondence           5       P1_current     100            27 0.222589  0.12        0.215 0.262818                 0.229901              0.183548          0.202004               0.550542              0.947476            0.519333              0.917367            0.209572            3.484259          0.029063                   0.893652            0.823288            2.70       0.262500
  sinkhorn_consensus_035 foreground_patch_correspondence           5     P2_consensus     100            27 0.213845  0.11        0.185 0.242655                 0.229901              0.183548          0.202004               0.550542              0.947476            0.519333              0.917367            0.209572            3.484259          0.029063                   0.893652            0.823288            2.81       0.273333
  sinkhorn_consensus_035 foreground_patch_correspondence           5 forward_02_cov70     100            27 0.243837  0.17        0.215 0.270292                 0.229901              0.183548          0.202004               0.550542              0.947476            0.519333              0.917367            0.209572            3.484259          0.029063                   0.893652            0.823288            2.97       0.291333
  sinkhorn_hungarian_035 foreground_patch_correspondence           2       P1_current     100            27 0.358976  0.26        0.325 0.366125                 0.135500              0.112167          0.119508               0.770000              0.791167            0.498750              0.738024            0.337996            1.642004          0.025495                   0.843077            0.784107            1.49       0.670000
  sinkhorn_hungarian_035 foreground_patch_correspondence           2     P2_consensus     100            27 0.358357  0.26        0.345 0.352125                 0.135500              0.112167          0.119508               0.770000              0.791167            0.498750              0.738024            0.337996            1.642004          0.025495                   0.843077            0.784107            1.56       0.630000
  sinkhorn_hungarian_035 foreground_patch_correspondence           2 forward_02_cov70     100            27 0.383512  0.31        0.385 0.371542                 0.135500              0.112167          0.119508               0.770000              0.791167            0.498750              0.738024            0.337996            1.642004          0.025495                   0.843077            0.784107            1.52       0.635000

## Results and decision

In [7]:
import pandas as pd
for file_name in (
    'primary_candidate_ranking.csv',
    'patch_association_summary.csv',
    'paired_asset_intervals.csv',
    'identity_coverage_vs_error.csv',
    'patch_fallback_summary.csv',
    'category_summary.csv',
    'family_summary.csv',
):
    print(file_name)
    display(pd.read_csv(EVALUATION_OUTPUT / 'shareable' / file_name))
display(json.loads((EVALUATION_OUTPUT / 'shareable/development_decision.json').read_text()))

primary_candidate_ranking.csv

,configuration_id,family,view_count,method,scenes,asset_groups,ap,top1,recall_at_2,auroc,...,identity_switch_rate,track_completeness,linked_node_fraction,singleton_fraction,mean_track_support,mean_edge_margin,mean_patch_match_fraction,mean_patch_entropy,winner_support,winner_purity
0,current_hungarian_035,global_baseline,3,P1_current,100,27,0.319980,0.23,0.295,0.305462,...,0.903500,0.735278,0.868418,0.231661,2.376201,NaN,NaN,NaN,2.15,0.476667
1,sinkhorn_hungarian_035,foreground_patch_correspondence,3,P1_current,100,27,0.290569,0.20,0.240,0.298190,...,0.913833,0.683889,0.774982,0.363147,2.110190,0.032582,0.890639,0.825871,1.82,0.460000
2,sinkhorn_consensus_035,foreground_patch_correspondence,3,P1_current,100,27,0.290312,0.20,0.260,0.293360,...,0.924167,0.675556,0.816625,0.306274,2.166810,0.032582,0.890639,0.825871,1.88,0.448333
3,reciprocal_hungarian_035,foreground_patch_correspondence,3,P1_current,100,27,0.292294,0.22,0.250,0.302475,...,0.900000,0.627222,0.750045,0.397817,2.034329,0.036735,0.378121,0.000000,1.72,0.480000

patch_association_summary.csv

,configuration_id,family,view_count,method,scenes,asset_groups,ap,top1,recall_at_2,auroc,...,identity_switch_rate,track_completeness,linked_node_fraction,singleton_fraction,mean_track_support,mean_edge_margin,mean_patch_match_fraction,mean_patch_entropy,winner_support,winner_purity
0,current_hungarian_035,global_baseline,2,P1_current,100,27,0.324845,0.24,0.300,0.319875,...,0.790333,0.517083,0.806968,0.257424,1.722576,NaN,NaN,NaN,1.56,0.650000
1,current_hungarian_035,global_baseline,2,P2_consensus,100,27,0.316679,0.22,0.310,0.308625,...,0.790333,0.517083,0.806968,0.257424,1.722576,NaN,NaN,NaN,1.64,0.590000
2,current_hungarian_035,global_baseline,2,forward_02_cov70,100,27,0.335833,0.27,0.325,0.323417,...,0.790333,0.517083,0.806968,0.257424,1.722576,NaN,NaN,NaN,1.59,0.610000
3,current_hungarian_035,global_baseline,3,P1_current,100,27,0.319980,0.23,0.295,0.305462,...,0.903500,0.735278,0.868418,0.231661,2.376201,NaN,NaN,NaN,2.15,0.476667
4,current_hungarian_035,global_baseline,3,P2_consensus,100,27,0.316694,0.21,0.290,0.313333,...,0.903500,0.735278,0.868418,0.231661,2.376201,NaN,NaN,NaN,2.15,0.455000
5,current_hungarian_035,global_baseline,3,forward_02_cov70,100,27,0.339835,0.24,0.355,0.335573,...,0.903500,0.735278,0.868418,0.231661,2.376201,NaN,NaN,NaN,2.10,0.426667
6,current_hungarian_035,global_baseline,5,P1_current,100,27,0.275236,0.19,0.295,0.301190,...,0.951667,0.664667,0.930616,0.179067,3.721607,NaN,NaN,NaN,2.88,0.301833
7,current_hungarian_035,global_baseline,5,P2_consensus,100,27,0.254242,0.15,0.270,0.274824,...,0.951667,0.664667,0.930616,0.179067,3.721607,NaN,NaN,NaN,2.94,0.299833
8,current_hungarian_035,global_baseline,5,forward_02_cov70,100,27,0.265845,0.17,0.280,0.299342,...,0.951667,0.664667,0.930616,0.179067,3.721607,NaN,NaN,NaN,3.10,0.313333
9,reciprocal_hungarian_035,foreground_patch_correspondence,2,P1_current,100,27,0.344512,0.26,0.320,0.348333,...,0.801667,0.511667,0.692000,0.393400,1.586600,0.029845,0.350988,0.000000,1.42,0.655000
10,reciprocal_hungarian_035,foreground_patch_correspondence,2,P2_consensus,100,27,0.344036,0.26,0.335,0.332470,...,0.801667,0.511667,0.692000,0.393400,1.586600,0.029845,0.350988,0.000000,1.49,0.645000
11,reciprocal_hungarian_035,foreground_patch_correspondence,2,forward_02_cov70,100,27,0.356345,0.29,0.350,0.339577,...,0.801667,0.511667,0.692000,0.393400,1.586600,0.029845,0.350988,0.000000,1.47,0.630000
12,reciprocal_hungarian_035,foreground_patch_correspondence,3,P1_current,100,27,0.292294,0.22,0.250,0.302475,...,0.900000,0.627222,0.750045,0.397817,2.034329,0.036735,0.378121,0.000000,1.72,0.480000
13,reciprocal_hungarian_035,foreground_patch_correspondence,3,P2_consensus,100,27,0.279982,0.18,0.255,0.305769,...,0.900000,0.627222,0.750045,0.397817,2.034329,0.036735,0.378121,0.000000,1.74,0.420000
14,reciprocal_hungarian_035,foreground_patch_correspondence,3,forward_02_cov70,100,27,0.320992,0.25,0.325,0.334086,...,0.900000,0.627222,0.750045,0.397817,2.034329,0.036735,0.378121,0.000000,1.68,0.446667
15,reciprocal_hungarian_035,foreground_patch_correspondence,5,P1_current,100,27,0.244216,0.19,0.230,0.297181,...,0.949167,0.582667,0.783941,0.434048,2.885546,0.030806,0.376166,0.000000,2.19,0.264333
16,reciprocal_hungarian_035,foreground_patch_correspondence,5,P2_consensus,100,27,0.222817,0.14,0.210,0.273438,...,0.949167,0.582667,0.783941,0.434048,2.885546,0.030806,0.376166,0.000000,2.19,0.247000
17,reciprocal_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,100,27,0.254603,0.20,0.255,0.304517,...,0.949167,0.582667,0.783941,0.434048,2.885546,0.030806,0.376166,0.000000,2.32,0.275333
18,sinkhorn_consensus_035,foreground_patch_correspondence,2,P1_current,100,27,0.358976,0.26,0.325,0.366125,...,0.791167,0.498750,0.738024,0.337996,1.642004,0.025495,0.843077,0.784107,1.49,0.670000
19,sinkhorn_consensus_035,foreground_patch_correspondence,2,P2_consensus,100,27,0.358357,0.26,0.345,0.352125,...,0.791167,0.498750,0.738024,0.337996,1.642004,0.025495,0.843077,0.784107,1.56,0.630000
20,sinkhorn_consensus_035,foreground_patch_correspondence,2,forward_02_cov70,100,27,0.383512,0.31,0.385,0.371542,...,0.791167,0.498750,0.738024,0.337996,1.642004,0.025495,0.843077,0.784107,1.52,0.635000
21,sinkhorn_consensus_035,foreground_patch_correspondence,3,P1_current,100,27,0.290312,0.20,0.260,0.293360,...,0.924167,0.675556,0.816625,0.306274,2.166810,0.032582,0.890639,0.825871,1.88,0.448333
22,sinkhorn_consensus_035,foreground_patch_correspondence,3,P2_consensus,100,27,0.301413,0.20,0.270,0.308339,...,0.924167,0.675556,0.816625,0.306274,2.166810,0.032582,0.890639,0.825871,1.87,0.423333
23,sinkhorn_consensus_035,foreground_patch_correspondence,3,forward_02_cov70,100,27,0.353337,0.28,0.355,0.362470,...,0.924167,0.675556,0.816625,0.306274,2.166810,0.032582,0.890639,0.825871,1.88,0.441667
24,sinkhorn_consensus_035,foreground_patch_correspondence,5,P1_current,100,27,0.222589,0.12,0.215,0.262818,...,0.947476,0.519333,0.917367,0.209572,3.484259,0.029063,0.893652,0.823288,2.70,0.262500
25,sinkhorn_consensus_035,foreground_patch_correspondence,5,P2_consensus,100,27,0.213845,0.11,0.185,0.242655,...,0.947476,0.519333,0.917367,0.209572,3.484259,0.029063,0.893652,0.823288,2.81,0.273333
26,sinkhorn_consensus_035,foreground_patch_correspondence,5,forward_02_cov70,100,27,0.243837,0.17,0.215,0.270292,...,0.947476,0.519333,0.917367,0.209572,3.484259,0.029063,0.893652,0.823288,2.97,0.291333
27,sinkhorn_hungarian_035,foreground_patch_correspondence,2,P1_current,100,27,0.358976,0.26,0.325,0.366125,...,0.791167,0.498750,0.738024,0.337996,1.642004,0.025495,0.843077,0.784107,1.49,0.670000
28,sinkhorn_hungarian_035,foreground_patch_correspondence,2,P2_consensus,100,27,0.358357,0.26,0.345,0.352125,...,0.791167,0.498750,0.738024,0.337996,1.642004,0.025495,0.843077,0.784107,1.56,0.630000
29,sinkhorn_hungarian_035,foreground_patch_correspondence,2,forward_02_cov70,100,27,0.383512,0.31,0.385,0.371542,...,0.791167,0.498750,0.738024,0.337996,1.642004,0.025495,0.843077,0.784107,1.52,0.635000
30,sinkhorn_hungarian_035,foreground_patch_correspondence,3,P1_current,100,27,0.290569,0.20,0.240,0.298190,...,0.913833,0.683889,0.774982,0.363147,2.110190,0.032582,0.890639,0.825871,1.82,0.460000
31,sinkhorn_hungarian_035,foreground_patch_correspondence,3,P2_consensus,100,27,0.277881,0.16,0.245,0.298908,...,0.913833,0.683889,0.774982,0.363147,2.110190,0.032582,0.890639,0.825871,1.79,0.391667
32,sinkhorn_hungarian_035,foreground_patch_correspondence,3,forward_02_cov70,100,27,0.317024,0.23,0.315,0.327289,...,0.913833,0.683889,0.774982,0.363147,2.110190,0.032582,0.890639,0.825871,1.74,0.421667
33,sinkhorn_hungarian_035,foreground_patch_correspondence,5,P1_current,100,27,0.269452,0.19,0.235,0.310997,...,0.942333,0.622667,0.801429,0.417527,2.970711,0.029063,0.893652,0.823288,2.27,0.301500
34,sinkhorn_hungarian_035,foreground_patch_correspondence,5,P2_consensus,100,27,0.242355,0.13,0.215,0.293275,...,0.942333,0.622667,0.801429,0.417527,2.970711,0.029063,0.893652,0.823288,2.17,0.248000
35,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,100,27,0.286571,0.21,0.275,0.334656,...,0.942333,0.622667,0.801429,0.417527,2.970711,0.029063,0.893652,0.823288,2.30,0.296667

paired_asset_intervals.csv

,view_count,method,measure,candidate,baseline,difference,ci_low,ci_high,asset_groups,scenes
0,2,P1_current,ap,reciprocal_hungarian_035,current_hungarian_035,0.019667,-0.026448,0.071569,27,100
1,2,P1_current,ap,sinkhorn_consensus_035,current_hungarian_035,0.034131,0.000479,0.085061,27,100
2,2,P1_current,ap,sinkhorn_hungarian_035,current_hungarian_035,0.034131,-0.000638,0.083362,27,100
3,2,P1_current,top1,reciprocal_hungarian_035,current_hungarian_035,0.020000,-0.029703,0.070000,27,100
4,2,P1_current,top1,sinkhorn_consensus_035,current_hungarian_035,0.020000,-0.020000,0.072165,27,100
...,...,...,...,...,...,...,...,...,...,...
76,5,forward_02_cov70,top1,sinkhorn_consensus_035,current_hungarian_035,0.000000,-0.071429,0.061224,27,100
77,5,forward_02_cov70,top1,sinkhorn_hungarian_035,current_hungarian_035,0.040000,-0.019802,0.101010,27,100
78,5,forward_02_cov70,identity_link_f1,reciprocal_hungarian_035,current_hungarian_035,-0.043785,-0.057074,-0.031662,27,100
79,5,forward_02_cov70,identity_link_f1,sinkhorn_consensus_035,current_hungarian_035,-0.030625,-0.042170,-0.019008,27,100
80,5,forward_02_cov70,identity_link_f1,sinkhorn_hungarian_035,current_hungarian_035,-0.025444,-0.038226,-0.012247,27,100

identity_coverage_vs_error.csv

,configuration_id,view_count,retained_fraction,retained_links,available_links,wrong_link_rate
0,reciprocal_hungarian_035,2,0.5,134,268,0.910448
1,reciprocal_hungarian_035,2,0.7,188,268,0.904255
2,reciprocal_hungarian_035,2,0.9,242,268,0.876033
3,reciprocal_hungarian_035,2,1.0,268,268,0.873134
4,reciprocal_hungarian_035,3,0.5,266,532,0.830827
5,reciprocal_hungarian_035,3,0.7,373,532,0.836461
6,reciprocal_hungarian_035,3,0.9,479,532,0.847599
7,reciprocal_hungarian_035,3,1.0,532,532,0.836466
8,reciprocal_hungarian_035,5,0.5,563,1126,0.769094
9,reciprocal_hungarian_035,5,0.7,789,1126,0.774398
10,reciprocal_hungarian_035,5,0.9,1014,1126,0.777120
11,reciprocal_hungarian_035,5,1.0,1126,1126,0.769982
12,sinkhorn_consensus_035,2,0.5,142,284,0.873239
13,sinkhorn_consensus_035,2,0.7,199,284,0.874372
14,sinkhorn_consensus_035,2,0.9,256,284,0.871094
15,sinkhorn_consensus_035,2,1.0,284,284,0.862676
16,sinkhorn_consensus_035,3,0.5,288,576,0.847222
17,sinkhorn_consensus_035,3,0.7,404,576,0.846535
18,sinkhorn_consensus_035,3,0.9,519,576,0.847784
19,sinkhorn_consensus_035,3,1.0,576,576,0.843750
20,sinkhorn_consensus_035,5,0.5,653,1306,0.787136
21,sinkhorn_consensus_035,5,0.7,915,1306,0.779235
22,sinkhorn_consensus_035,5,0.9,1176,1306,0.781463
23,sinkhorn_consensus_035,5,1.0,1306,1306,0.775651
24,sinkhorn_hungarian_035,2,0.5,142,284,0.873239
25,sinkhorn_hungarian_035,2,0.7,199,284,0.874372
26,sinkhorn_hungarian_035,2,0.9,256,284,0.871094
27,sinkhorn_hungarian_035,2,1.0,284,284,0.862676
28,sinkhorn_hungarian_035,3,0.5,277,554,0.823105
29,sinkhorn_hungarian_035,3,0.7,388,554,0.811856
30,sinkhorn_hungarian_035,3,0.9,499,554,0.817635
31,sinkhorn_hungarian_035,3,1.0,554,554,0.810469
32,sinkhorn_hungarian_035,5,0.5,581,1162,0.764200
33,sinkhorn_hungarian_035,5,0.7,814,1162,0.772727
34,sinkhorn_hungarian_035,5,0.9,1046,1162,0.767686
35,sinkhorn_hungarian_035,5,1.0,1162,1162,0.763339

patch_fallback_summary.csv

                     coverage  fallback_count
0  foreground_patch_selection               0

category_summary.csv

,configuration_id,family,view_count,method,category,ap,top1,identity_link_f1
0,current_hungarian_035,global_baseline,2,P1_current,apple,0.000000,0.000000,0.000000
1,current_hungarian_035,global_baseline,2,P1_current,bottle,0.145833,0.000000,0.083333
2,current_hungarian_035,global_baseline,2,P1_current,bowl,0.500000,0.333333,0.111111
3,current_hungarian_035,global_baseline,2,P1_current,bread,0.098214,0.000000,0.083333
4,current_hungarian_035,global_baseline,2,P1_current,bunny,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
967,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,monkey,0.055556,0.000000,0.139040
968,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,mouse,0.122222,0.000000,0.120430
969,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,orange,0.277778,0.333333,0.152836
970,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,pig,0.500000,0.333333,0.193791
971,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,shark,0.041667,0.000000,0.093799

family_summary.csv

,configuration_id,family,view_count,method,families,ap,top1,identity_link_f1
0,current_hungarian_035,global_baseline,2,P1_current,bump,0.287879,0.181818,0.088889
1,current_hungarian_035,global_baseline,2,P1_current,crack,0.362745,0.294118,0.075630
2,current_hungarian_035,global_baseline,2,P1_current,crack+disc,0.208333,0.250000,0.125000
3,current_hungarian_035,global_baseline,2,P1_current,crack+frac,0.195982,0.125000,0.125992
4,current_hungarian_035,global_baseline,2,P1_current,defr,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...
391,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,frac,0.370175,0.210526,0.192626
392,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,miss,0.462500,0.375000,0.329436
393,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,miss+tran,0.300000,0.500000,0.244152
394,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,rota,0.000000,0.000000,0.118026
395,sinkhorn_hungarian_035,foreground_patch_correspondence,5,forward_02_cov70,tran,0.500000,0.500000,0.217797

{'baseline': 'current_hungarian_035',
 'prediction_producer': 'dinov2-small-foreground-patch-correspondence',
 'primary_route': 'automatic masks, predicted identity, three views',
 'primary_scorer': 'P1_current',
 'promotion': 'No candidate passed the joint identity, ranking and anti-fragmentation rule.',
 'protected_data_used': False,
 'review_candidate': 'sinkhorn_hungarian_035',
 'scientific_result': True,
 'selected_configuration': 'current_hungarian_035',
 'split_changed': False,
 'status': 'retain_current'}

## Figures and private examples

Summary figures compare identity quality, odd-one-out accuracy, and the wrong-link rate as lower-confidence links are removed. The private gallery shows fixed improvements, regressions and representative cases. Red marks the selected identity, green marks the reference unusual object, and blue marks other automatic candidates.

In [8]:
from IPython.display import Image as NotebookImage, display
for figure in sorted((EVALUATION_OUTPUT / 'shareable/figures').glob('*.png')):
    print(figure.name)
    display(NotebookImage(filename=str(figure)))
gallery = json.loads((EVALUATION_OUTPUT / 'private/gallery_manifest.json').read_text())
for item in gallery['examples']:
    print(item['file'], item['selection_reason'])
    display(NotebookImage(filename=str(EVALUATION_OUTPUT / 'private/figures' / item['file'])))

identity_coverage_vs_error.png

identity_vs_top1.png

primary_top1_comparison.png

identity_example_01.png improvement

identity_example_02.png improvement

identity_example_03.png improvement

identity_example_04.png improvement

identity_example_05.png regression

identity_example_06.png regression

identity_example_07.png regression

identity_example_08.png regression

identity_example_09.png fixed_hash_sample

identity_example_10.png fixed_hash_sample

identity_example_11.png fixed_hash_sample

identity_example_12.png fixed_hash_sample

## Post-compute ClearML upload

ClearML runs only after the scientific outputs are sealed. It receives aggregate tables, decisions and summary figures. Private images, labels, per-scene records, model inputs and credentials are excluded. Tracking failure cannot trigger another GPU run.

In [9]:
if tracking_credentials():
    try:
        subprocess.run([
            str(PYTHON), '-m', 'pip', 'install', '--retries', '1', '--timeout', '30',
            '--only-binary=:all:', '--upgrade', '--target', str(PACKAGE_ROOT),
            '-r', str(SOURCE / 'requirements/identity-patch-association-tracking.txt'),
        ], check=True, timeout=180)
        subprocess.run([
            str(PYTHON), str(SOURCE / 'scripts/log_identity_patch_association.py'),
            '--evidence', str(EVALUATION_OUTPUT),
        ], check=True, timeout=300)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
        print(f'ClearML upload remains retryable: {type(error).__name__}')
else:
    print('ClearML secrets are unavailable. Scientific outputs are complete and unchanged.')

ClearML secrets are unavailable. Scientific outputs are complete and unchanged.

## Download package

In [10]:
RESULT_ZIP = WORKING_ROOT / 'identity-patch-study-results.zip'
with ZipFile(RESULT_ZIP, 'w', compression=ZIP_DEFLATED, compresslevel=6) as handle:
    for root in (PREDICTION_OUTPUT, EVALUATION_OUTPUT):
        for path in sorted(root.rglob('*')):
            if path.is_file():
                handle.write(path, Path(root.name) / path.relative_to(root))
    for path in sorted(WORKING_ROOT.glob('identity-patch-*.log')):
        handle.write(path, Path('logs') / path.name)
with ZipFile(RESULT_ZIP) as handle:
    if handle.testzip() is not None:
        raise ValueError('The result archive failed its integrity check')
print(json.dumps({
    'result_zip': str(RESULT_ZIP),
    'size_bytes': RESULT_ZIP.stat().st_size,
    'prediction_output': str(PREDICTION_OUTPUT),
    'evaluation_output': str(EVALUATION_OUTPUT),
    'decision': json.loads((EVALUATION_OUTPUT / 'shareable/development_decision.json').read_text()),
}, indent=2, sort_keys=True))

{
  "decision": {
    "baseline": "current_hungarian_035",
    "prediction_producer": "dinov2-small-foreground-patch-correspondence",
    "primary_route": "automatic masks, predicted identity, three views",
    "primary_scorer": "P1_current",
    "promotion": "No candidate passed the joint identity, ranking and anti-fragmentation rule.",
    "protected_data_used": false,
    "review_candidate": "sinkhorn_hungarian_035",
    "scientific_result": true,
    "selected_configuration": "current_hungarian_035",
    "split_changed": false,
    "status": "retain_current"
  },
  "evaluation_output": "/kaggle/working/identity-patch-evaluation",
  "prediction_output": "/kaggle/working/identity-patch-predictions",
  "result_zip": "/kaggle/working/identity-patch-study-results.zip",
  "size_bytes": 4532295
}

## Interpretation rule

Promote a candidate only if the paired asset-group interval improves identity-link F1 and average precision, top-1 and recall at two do not regress, and linked coverage and singleton rate remain acceptable. Otherwise retain the current Hungarian method and use the confidence evidence to identify cases that need optional review.