# 08I: Development cross-view identity refinement

This notebook tests whether foreground DINO patch pooling improves object association across uploaded views. It uses the existing 100-scene development screen and does not change the 2,000-scene split.

DINOv2-small, LocateAnything proposals, SAM 2.1 masks and all existing scorer outputs remain fixed. The notebook reuses the locked 08G global embeddings and only computes the foreground patch descriptors that were not retained after scoring.

Notebook file: `08i-development-identity-refinement.ipynb`.

## Saved-output evidence copy

This notebook records the completed run for repository review. Its code and markdown match the clean runnable notebook. Private scene visuals and identifier-bearing output were removed. Safe aggregate tables and charts were retained.

Run stage: `08I-screen100`  
Clean notebook SHA-256: `e955c4a7a1f619f6ccc8d050293fd4d3a11726507cda72b5cc9b0f19198e8e1a`  
Downloaded saved-output SHA-256: `bca913030711c7fc5dc4d49e365d23742087bde022055513f5fe5145a3115f39`

## Study boundary

The automatic route is the main route because the web application will not receive reference boxes or masks. The notebook compares two, three and five selected views. It keeps the current global DINO identity method as the baseline and adds local and hybrid descriptors built from foreground patch tokens.

Lock prediction-only identity candidates before any development correspondence is opened. Only then open development correspondence for evaluation. Labels, categories, asset groups and source object identities cannot enter descriptor extraction or matching.

No arbitrary accuracy gate is used. Report actual identity precision, identity recall, identity F1, average precision, top-1 accuracy, recall at two and subgroup results. The highest development row is a candidate for review, not an automatic promotion or an untouched test result.

## Paths and runtime settings

Attach four private resources: the identity-refinement source package, the existing scoring model-input package, the completed 08G screen output and the matching development evaluator. A recovery archive is optional for a fresh run and required only for an intentional continuation.

In [1]:
from pathlib import Path, PurePosixPath
from hashlib import sha256
from zipfile import ZipFile
import json
import os
import shutil
import stat
import subprocess
import sys

INPUT_ROOT = Path('/kaggle/input')
WORKING_ROOT = Path('/kaggle/working')
PACKAGE_ROOT = WORKING_ROOT / 'identity-packages'
PREDICTION_OUTPUT = WORKING_ROOT / 'identity-refinement-predictions'
EVALUATION_OUTPUT = WORKING_ROOT / 'identity-refinement-evaluation'
PYTHON = Path(sys.executable)
EXPECT_RECOVERY = False

mount_roots = []
for pattern in ('*', 'datasets/*/*', 'datasets/*/*/versions/*', 'notebooks/*/*', 'notebooks/*/*/versions/*'):
    mount_roots.extend(path.resolve() for path in INPUT_ROOT.glob(pattern) if path.is_dir())
mount_roots = sorted(set(mount_roots))
source_mounts = [path for path in mount_roots if any(part.startswith('vpi-identity-refinement-source') for part in path.parts[-4:])]
source_markers = []
for source_mount in source_mounts:
    source_markers.extend(path for path in source_mount.rglob('identity_refinement.py') if path.is_file())
source_candidates = [path.parents[3] for path in sorted(set(source_markers)) if (path.parents[3] / 'scripts/run_identity_refinement.py').is_file()]
if not source_candidates:
    archives = []
    for source_mount in source_mounts:
        archives.extend(path for path in source_mount.rglob('identity-refinement-source-*.zip') if path.is_file())
    archives = sorted(set(archives))
    if len(archives) != 1:
        raise ValueError(f'Expected one identity-refinement source archive, found {len(archives)}')
    extraction = WORKING_ROOT / 'identity-source'
    temporary = extraction.with_name(extraction.name + '.incomplete')
    if extraction.exists() or temporary.exists():
        raise FileExistsError('Source extraction destination is not empty')
    temporary.mkdir(parents=True)
    with ZipFile(archives[0]) as handle:
        entries = handle.infolist()
        names = [entry.filename for entry in entries]
        if not entries or len(names) != len(set(names)) or handle.testzip() is not None:
            raise ValueError('Source archive is empty, duplicated or corrupt')
        for entry in entries:
            relative = PurePosixPath(entry.filename)
            mode = entry.external_attr >> 16
            if entry.is_dir() or relative.is_absolute() or any(part in ('', '.', '..') for part in relative.parts) or stat.S_ISLNK(mode):
                raise ValueError('Source archive contains an unsafe path')
            destination = temporary.joinpath(*relative.parts)
            destination.parent.mkdir(parents=True, exist_ok=True)
            with handle.open(entry) as source_stream, destination.open('xb') as target_stream:
                shutil.copyfileobj(source_stream, target_stream, length=1024 * 1024)
    temporary.replace(extraction)
    source_candidates = [extraction / 'identity-refinement']
if len(source_candidates) != 1:
    raise ValueError(f'Expected one identity-refinement source root, found {len(source_candidates)}')
SOURCE = source_candidates[0]
sys.path.insert(0, str(SOURCE / 'scripts'))
from kaggle_mounts import find_prediction, find_recovery, materialize_sealed_resource
from scoring_comparison_runtime import run_bounded, tracking_credentials

## Runtime preparation

Install the pinned add-ons into a run-local package directory. Retain Kaggle's CUDA-compatible PyTorch build. Package installation, tests and input validation are bounded and finish before model loading.

In [2]:
PACKAGE_ROOT.mkdir(parents=True, exist_ok=True)
subprocess.run([
    str(PYTHON), '-m', 'pip', 'install', '--disable-pip-version-check',
    '--retries', '1', '--timeout', '60', '--only-binary=:all:',
    '--upgrade', '--target', str(PACKAGE_ROOT),
    '-r', str(SOURCE / 'requirements/identity-refinement.txt'),
], check=True, timeout=600)
os.environ['PYTHONPATH'] = os.pathsep.join([
    str(SOURCE / 'src'), str(PACKAGE_ROOT), os.environ.get('PYTHONPATH', '')
]).rstrip(os.pathsep)
sys.path.insert(0, str(PACKAGE_ROOT))
RUNNER = SOURCE / 'scripts/run_identity_refinement.py'
test_env = dict(os.environ, PYTHONDONTWRITEBYTECODE='1', MPLCONFIGDIR=str(WORKING_ROOT / 'matplotlib'))
subprocess.run([
    str(PYTHON), '-m', 'pytest', '-p', 'no:cacheprovider',
    str(SOURCE / 'tests/test_identity_patch_matching.py'),
    str(SOURCE / 'tests/test_identity_refinement_contract.py'), '-q',
], check=True, cwd=WORKING_ROOT, env=test_env, timeout=300)

Collecting transformers==5.14.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading transformers-5.14.1-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub==1.26.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading huggingface_hub-1.26.1-py3-none-any.whl.metadata (16 kB)
Collecting numpy==2.5.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 5))
  Downloading numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting pandas==2.3.3 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 6))
  Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 2.6 MB/s eta 0:00:00
Collecting pillow==12.3.0 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 7))
  Downloading pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting scipy==1.16.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 8))
  Downloading scipy-1.16.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 4.1 MB/s eta 0:00:00
Collecting matplotlib==3.10.8 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 9))
  Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 4.0 MB/s eta 0:00:00
Collecting nbformat==5.11.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading nbformat-5.11.1-py3-none-any.whl.metadata (3.7 kB)
Collecting pytest==9.1.1 (from -r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 11))
  Downloading pytest-9.1.1-py3-none-any.whl.metadata (7.6 kB)
Collecting packaging>=20.0 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting pyyaml>=5.1 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting regex>=2025.10.22 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading regex-2026.9.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 2.2 MB/s eta 0:00:00
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting typer (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading typer-0.27.2-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.8.0 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting tqdm>=4.60 (from transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading tqdm-4.70.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.4/57.4 kB 2.4 MB/s eta 0:00:00
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading click-8.5.0-py3-none-any.whl.metadata (2.6 kB)
Collecting filelock>=3.10.0 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading filelock-3.32.6-py3-none-any.whl.metadata (2.0 kB)
Collecting fsspec>=2023.5.0 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting python-dateutil>=2.8.2 (from pandas==2.3.3->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 6))
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas==2.3.3->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 6))
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas==2.3.3->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 6))
  Downloading tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 9))
  Downloading contourpy-1.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 9))
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 9))
  Downloading fonttools-4.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 8.6 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 9))
  Downloading kiwisolver-1.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.2 kB)
Collecting pyparsing>=3 (from matplotlib==3.10.8->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 9))
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting fastjsonschema>=2.15 (from nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading fastjsonschema-2.22.2-py3-none-any.whl.metadata (2.1 kB)
Collecting jsonschema>=2.6 (from nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting jupyter-core!=5.0.*,>=4.12 (from nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading jupyter_core-5.9.1-py3-none-any.whl.metadata (1.5 kB)
Collecting traitlets>=5.1 (from nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading traitlets-5.16.1-py3-none-any.whl.metadata (10 kB)
Collecting iniconfig>=1.0.1 (from pytest==9.1.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 11))
  Downloading iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting pluggy<2,>=1.5 (from pytest==9.1.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 11))
  Downloading pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Collecting pygments>=2.7.2 (from pytest==9.1.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 11))
  Downloading pygments-2.21.0-py3-none-any.whl.metadata (2.5 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Collecting certifi (from httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub==1.26.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 4))
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting platformdirs>=2.5 (from jupyter-core!=5.0.*,>=4.12->nbformat==5.11.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 10))
  Downloading platformdirs-4.11.8-py3-none-any.whl.metadata (5.5 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas==2.3.3->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 6))
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting shellingham>=1.3.0 (from typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers==5.14.1->-r /kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/requirements/identity-refinement.txt (line 3))
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading transformers-5.14.1-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 89.8 MB/s eta 0:00:00
Downloading huggingface_hub-1.26.1-py3-none-any.whl (780 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.8/780.8 kB 45.0 MB/s eta 0:00:00
Downloading numpy-2.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 53.6 MB/s eta 0:00:00
Downloading pandas-2.3.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 71.6 MB/s eta 0:00:00
Downloading pillow-12.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 74.8 MB/s eta 0:00:00
Downloading scipy-1.16.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (35.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.2/35.2 MB 40.7 MB/s eta 0:00:00
Downloading matplotlib-3.10.8-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (8.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 84.3 MB/s eta 0:00:00
Downloading nbformat-5.11.1-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 6.0 MB/s eta 0:00:00
Downloading pytest-9.1.1-py3-none-any.whl (386 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.5/386.5 kB 29.7 MB/s eta 0:00:00
Downloading click-8.5.0-py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.3/125.3 kB 9.1 MB/s eta 0:00:00
Downloading contourpy-1.4.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (383 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.2/383.2 kB 26.7 MB/s eta 0:00:00
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fastjsonschema-2.22.2-py3-none-any.whl (27 kB)
Downloading filelock-3.32.6-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.2/100.2 kB 7.8 MB/s eta 0:00:00
Downloading fonttools-4.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 89.4 MB/s eta 0:00:00
Downloading fsspec-2026.7.0-py3-none-any.whl (206 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 206.6/206.6 kB 15.5 MB/s eta 0:00:00
Downloading hf_xet-1.6.0-cp38-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 97.9 MB/s eta 0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 5.9 MB/s eta 0:00:00
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 6.8 MB/s eta 0:00:00
Downloading iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.6/90.6 kB 6.4 MB/s eta 0:00:00
Downloading jupyter_core-5.9.1-py3-none-any.whl (29 kB)
Downloading kiwisolver-1.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 49.9 MB/s eta 0:00:00
Downloading packaging-26.3-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.0/130.0 kB 10.5 MB/s eta 0:00:00
Downloading pluggy-1.6.0-py3-none-any.whl (20 kB)
Downloading pygments-2.21.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 58.3 MB/s eta 0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.8/122.8 kB 9.6 MB/s eta 0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 13.8 MB/s eta 0:00:00
Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.3/508.3 kB 29.9 MB/s eta 0:00:00
Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 46.7 MB/s eta 0:00:00
Downloading regex-2026.9.10-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (804 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.6/804.6 kB 39.9 MB/s eta 0:00:00
Downloading safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 516.0/516.0 kB 33.3 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 61.5 MB/s eta 0:00:00
Downloading tqdm-4.70.1-py3-none-any.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.2/80.2 kB 6.0 MB/s eta 0:00:00
Downloading traitlets-5.16.1-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.2/86.2 kB 6.0 MB/s eta 0:00:00
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 3.2 MB/s eta 0:00:00
Downloading tzdata-2026.4-py2.py3-none-any.whl (347 kB)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
datasets 5.0.0 requires fsspec[http]<=2026.4.0,>=2023.1.0, but you have fsspec 2026.7.0 which is incompatible.
ydata-profiling 4.18.4 requires matplotlib<=3.10,>=3.5, but you have matplotlib 3.10.8 which is incompatible.
ydata-profiling 4.18.4 requires numpy<2.4,>=1.22, but you have numpy 2.5.1 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
dopamine-rl 4.1.2 requires gym<=0.25.2, but you have gym 0.26.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.
bigframes 2.39.0 requires rich<14,>=12.4.4, but you have rich 15.0.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.1 which is incompatible.
pyiceberg 0.11.1 requires rich<15.0.0,>=10.11.0, but you have rich 15.0.0 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.7.0 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.3.0 which is incompatible.

Successfully installed annotated-doc-0.0.5 anyio-4.15.1 attrs-26.1.0 certifi-2026.7.22 click-8.5.0 contourpy-1.4.0 cycler-0.12.1 fastjsonschema-2.22.2 filelock-3.32.6 fonttools-4.65.0 fsspec-2026.7.0 h11-0.16.0 hf-xet-1.6.0 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.26.1 idna-3.19 iniconfig-2.3.0 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 jupyter-core-5.9.1 kiwisolver-1.5.1 markdown-it-py-4.2.0 matplotlib-3.10.8 mdurl-0.1.2 nbformat-5.11.1 numpy-2.5.1 packaging-26.3 pandas-2.3.3 pillow-12.3.0 platformdirs-4.11.8 pluggy-1.6.0 pygments-2.21.0 pyparsing-3.3.2 pytest-9.1.1 python-dateutil-2.9.0.post0 pytz-2026.3.post1 pyyaml-6.0.3 referencing-0.37.0 regex-2026.9.10 rich-15.0.0 rpds-py-2026.6.3 safetensors-0.8.0 scipy-1.16.1 shellingham-1.5.4 six-1.17.0 tokenizers-0.22.2 tqdm-4.70.1 traitlets-5.16.1 transformers-5.14.1 typer-0.27.2 typing-extensions-4.16.0 tzdata-2026.4
........                                                                 [100%]
8 passed in 1.64s

CompletedProcess(args=['/usr/bin/python3', '-m', 'pytest', '-p', 'no:cacheprovider', '/kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/tests/test_identity_patch_matching.py', '/kaggle/input/datasets/esreekarreddy/vpi-identity-refinement-source/identity-refinement/tests/test_identity_refinement_contract.py', '-q'], returncode=0)

## Locked input discovery

Materialise the existing model-only package and locate the completed 08G screen output by its lock binding. The evaluator resource is not opened during this phase.

In [3]:
MODEL_INPUT = materialize_sealed_resource(
    INPUT_ROOT,
    kind='model-input',
    archive_name='scoring-comparison-model-input.zip',
    archive_sha256='6d6b45aa211ea595524729123870307ee5295ada48e6fd8f1898935f477b6901',
    destination=WORKING_ROOT / 'identity-model-resource',
    expected_lock_sha256='9baa53454d2482caf8240e7a8b591a6e9e9646dd160c5b3abdc8bd17265ebda1',
)
model_lock_sha256 = sha256((MODEL_INPUT / 'artifact_lock.json').read_bytes()).hexdigest()
SCORING = find_prediction(INPUT_ROOT, expected_input_lock_sha256=model_lock_sha256)
if not (SCORING / 'feature_lock.json').is_file():
    raise FileNotFoundError('Attach the completed 08G screen output with its feature lock')
run_bounded([
    str(PYTHON), str(RUNNER), 'preflight',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--output', str(PREDICTION_OUTPUT),
], WORKING_ROOT / 'identity-input-validation.log', idle_seconds=300, total_seconds=900)

{'scene_count': 100, 'scenes': ['[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]', '[protected identifier removed]'], 'view_count': 8, 'configuration_count_per_scene': 63, 'model_input_lock_sha256': '9baa53454d2482caf8240e7a8b591a6e9e9646dd160c5b3abdc8bd17265ebda1', 'scoring_prediction_lock_sha256': '12ce9bfc2bb401c29621d91000c53ff4fd39504fc28e55ff8a921e0b5443690d'}

## Checked recovery

Every completed scene has an atomic checkpoint and a matching receipt. The run binding covers inputs, source, dependencies and the fixed protocol. Kaggle recovery must be attached as the original `.zip.bin` bytes together with its manifest. Expanded, incomplete, duplicated or differently bound recovery data is rejected before inference.

In [4]:
# A fresh run must ignore unrelated recovery files mounted by Kaggle.
RECOVERY = find_recovery(INPUT_ROOT) if EXPECT_RECOVERY else None
print(json.dumps({
    'event': 'recovery_discovery',
    'expected': EXPECT_RECOVERY,
    'attached': RECOVERY is not None,
    'archive': RECOVERY[0].name if RECOVERY else None,
}, sort_keys=True))
if EXPECT_RECOVERY and RECOVERY is None:
    raise FileNotFoundError('This continuation run requires one sealed recovery archive and manifest')
recovery_arguments = [] if RECOVERY is None else [
    '--recovery-bundle', str(RECOVERY[0]),
    '--recovery-manifest', str(RECOVERY[1]),
]

{"archive": null, "attached": false, "event": "recovery_discovery", "expected": false}

## Lock prediction-only identity candidates

Use one GPU. The runner downloads the pinned DINOv2-small revision, loads it on CPU, moves it to CUDA and reports each checkpoint. It recomputes foreground patch descriptors for the eight views used across the two, three and five-view comparisons. Global embeddings and all anomaly scores are reused from 08G.

A 15-minute silent limit stops a stalled worker. A four-hour total limit prevents unattended GPU use. These are runtime limits, not accuracy gates. A failure preserves the newest recovery package; it does not justify repeating completed scenes.

In [5]:
run_bounded([
    str(PYTHON), str(RUNNER), 'predict',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--output', str(PREDICTION_OUTPUT), *recovery_arguments,
], WORKING_ROOT / 'identity-prediction.log', idle_seconds=900, total_seconds=14400)
run_bounded([
    str(PYTHON), str(RUNNER), 'verify',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--output', str(PREDICTION_OUTPUT),
], WORKING_ROOT / 'identity-prediction-validation.log', idle_seconds=300, total_seconds=600)
display(json.loads((PREDICTION_OUTPUT / 'run_status.json').read_text()))
display(json.loads((PREDICTION_OUTPUT / 'progress.json').read_text()))

{'event': 'runtime_ready', 'gpu': 'Tesla T4', 'visible_gpus': 2, 'devices_used': 1, 'output_free_bytes': 20351041536}
{"event": "model_load_start", "revision": "ed25f3a31f01632728cabb09d1542f84ab7b0056"}
{'event': 'model_download_start', 'revision': 'ed25f3a31f01632728cabb09d1542f84ab7b0056'}

Fetching 6 files:   0%|          | 0/6 [00:00<?, ?it/s]Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Fetching 6 files:  33%|███▎      | 2/6 [00:00<00:00, 12.79it/s]
Fetching 6 files:  83%|████████▎ | 5/6 [00:01<00:00,  3.69it/s]
Fetching 6 files: 100%|██████████| 6/6 [00:06<00:00,  1.46s/it]
Fetching 6 files: 100%|██████████| 6/6 [00:06<00:00,  1.06s/it]
{'event': 'model_download_complete', 'snapshot': 'ed25f3a31f01632728cabb09d1542f84ab7b0056'}

Loading weights:   0%|          | 0/223 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 223/223 [00:00<00:00, 2874.25it/s]
{'event': 'model_cpu_ready'}
{'event': 'model_cuda_ready', 'allocated_bytes': 88226304}
{"event": "model_ready"}
{"event": "scene_complete", "scene_number": 1, "total": 100}
{"event": "scene_complete", "scene_number": 2, "total": 100}
{"event": "scene_complete", "scene_number": 3, "total": 100}
{"event": "scene_complete", "scene_number": 4, "total": 100}
{"event": "scene_complete", "scene_number": 5, "total": 100}
{"event": "scene_complete", "scene_number": 6, "total": 100}
{"event": "scene_complete", "scene_number": 7, "total": 100}
{"event": "scene_complete", "scene_number": 8, "total": 100}
{"event": "scene_complete", "scene_number": 9, "total": 100}
{"event": "scene_complete", "scene_number": 10, "total": 100}
{"event": "scene_complete", "scene_number": 11, "total": 100}
{"event": "scene_complete", "scene_number": 12, "total": 100}
{"event": "scene_complete", "scene_number": 13, "total": 100}
{"event": "scene_complete", "scene_number": 14, "total": 100}
{"event": "scene_complete", "scene_number": 15, "total": 100}
{"event": "scene_complete", "scene_number": 16, "total": 100}
{"event": "scene_complete", "scene_number": 17, "total": 100}
{"event": "scene_complete", "scene_number": 18, "total": 100}
{"event": "scene_complete", "scene_number": 19, "total": 100}
{"event": "scene_complete", "scene_number": 20, "total": 100}
{"event": "scene_complete", "scene_number": 21, "total": 100}
{"event": "scene_complete", "scene_number": 22, "total": 100}
{"event": "scene_complete", "scene_number": 23, "total": 100}
{"event": "scene_complete", "scene_number": 24, "total": 100}
{"event": "scene_complete", "scene_number": 25, "total": 100}
{"event": "scene_complete", "scene_number": 26, "total": 100}
{"event": "scene_complete", "scene_number": 27, "total": 100}
{"event": "scene_complete", "scene_number": 28, "total": 100}
{"event": "scene_complete", "scene_number": 29, "total": 100}
{"event": "scene_complete", "scene_number": 30, "total": 100}
{"event": "scene_complete", "scene_number": 31, "total": 100}
{"event": "scene_complete", "scene_number": 32, "total": 100}
{"event": "scene_complete", "scene_number": 33, "total": 100}
{"event": "scene_complete", "scene_number": 34, "total": 100}
{"event": "scene_complete", "scene_number": 35, "total": 100}
{"event": "scene_complete", "scene_number": 36, "total": 100}
{"event": "scene_complete", "scene_number": 37, "total": 100}
{"event": "scene_complete", "scene_number": 38, "total": 100}
{"event": "scene_complete", "scene_number": 39, "total": 100}
{"event": "scene_complete", "scene_number": 40, "total": 100}
{"event": "scene_complete", "scene_number": 41, "total": 100}
{"event": "scene_complete", "scene_number": 42, "total": 100}
{"event": "scene_complete", "scene_number": 43, "total": 100}
{"event": "scene_complete", "scene_number": 44, "total": 100}
{"event": "scene_complete", "scene_number": 45, "total": 100}
{"event": "scene_complete", "scene_number": 46, "total": 100}
{"event": "scene_complete", "scene_number": 47, "total": 100}
{"event": "scene_complete", "scene_number": 48, "total": 100}
{"event": "scene_complete", "scene_number": 49, "total": 100}
{"event": "scene_complete", "scene_number": 50, "total": 100}
{"event": "scene_complete", "scene_number": 51, "total": 100}
{"event": "scene_complete", "scene_number": 52, "total": 100}
{"event": "scene_complete", "scene_number": 53, "total": 100}
{"event": "scene_complete", "scene_number": 54, "total": 100}
{"event": "scene_complete", "scene_number": 55, "total": 100}
{"event": "scene_complete", "scene_number": 56, "total": 100}
{"event": "scene_complete", "scene_number": 57, "total": 100}
{"event": "scene_complete", "scene_number": 58, "total": 100}
{"event": "scene_complete", "scene_number": 59, "total": 100}
{"event": "scene_complete", "scene_number": 60, "total": 100}
{"event": "scene_complete", "scene_number": 61, "total": 100}
{"event": "scene_complete", "scene_number": 62, "total": 100}
{"event": "scene_complete", "scene_number": 63, "total": 100}
{"event": "scene_complete", "scene_number": 64, "total": 100}
{"event": "scene_complete", "scene_number": 65, "total": 100}
{"event": "scene_complete", "scene_number": 66, "total": 100}
{"event": "scene_complete", "scene_number": 67, "total": 100}
{"event": "scene_complete", "scene_number": 68, "total": 100}
{"event": "scene_complete", "scene_number": 69, "total": 100}
{"event": "scene_complete", "scene_number": 70, "total": 100}
{"event": "scene_complete", "scene_number": 71, "total": 100}
{"event": "scene_complete", "scene_number": 72, "total": 100}
{"event": "scene_complete", "scene_number": 73, "total": 100}
{"event": "scene_complete", "scene_number": 74, "total": 100}
{"event": "scene_complete", "scene_number": 75, "total": 100}
{"event": "scene_complete", "scene_number": 76, "total": 100}
{"event": "scene_complete", "scene_number": 77, "total": 100}
{"event": "scene_complete", "scene_number": 78, "total": 100}
{"event": "scene_complete", "scene_number": 79, "total": 100}
{"event": "scene_complete", "scene_number": 80, "total": 100}
{"event": "scene_complete", "scene_number": 81, "total": 100}
{"event": "scene_complete", "scene_number": 82, "total": 100}
{"event": "scene_complete", "scene_number": 83, "total": 100}
{"event": "scene_complete", "scene_number": 84, "total": 100}
{"event": "scene_complete", "scene_number": 85, "total": 100}
{"event": "scene_complete", "scene_number": 86, "total": 100}
{"event": "scene_complete", "scene_number": 87, "total": 100}
{"event": "scene_complete", "scene_number": 88, "total": 100}
{"event": "scene_complete", "scene_number": 89, "total": 100}
{"event": "scene_complete", "scene_number": 90, "total": 100}
{"event": "scene_complete", "scene_number": 91, "total": 100}
{"event": "scene_complete", "scene_number": 92, "total": 100}
{"event": "scene_complete", "scene_number": 93, "total": 100}
{"event": "scene_complete", "scene_number": 94, "total": 100}
{"event": "scene_complete", "scene_number": 95, "total": 100}
{"event": "scene_complete", "scene_number": 96, "total": 100}
{"event": "scene_complete", "scene_number": 97, "total": 100}
{"event": "scene_complete", "scene_number": 98, "total": 100}
{"event": "scene_complete", "scene_number": 99, "total": 100}
{"event": "scene_complete", "scene_number": 100, "total": 100}
{'event': 'gpu_summary', 'peak_allocated_bytes': 163530240}

{'scene_count': 100, 'status': 'complete'}

{'complete_scenes': 100, 'expected_scenes': 100}

## Only then open development correspondence

The prediction lock now fixes every descriptor and match before labels are read. The evaluator checks true cross-view identity and the downstream odd-one-out ranking. The automatic route remains the denominator even when proposals are missing or tracks are mixed.

In [6]:
EVALUATOR = materialize_sealed_resource(
    INPUT_ROOT,
    kind='evaluator-only',
    archive_name='scoring-comparison-evaluator-only.zip',
    archive_sha256='86ac512005af5fdceb64c0fb666998832b8ee08ef96d1fccca23c6e35f420c12',
    destination=WORKING_ROOT / 'identity-evaluator-resource',
    expected_lock_sha256='8012cd20c63b3788f861f2ba991b3181a0c1666f26e176beeee370228c8500c3',
)
run_bounded([
    str(PYTHON), str(RUNNER), 'evaluate',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--predictions', str(PREDICTION_OUTPUT), '--evaluator', str(EVALUATOR),
    '--output', str(EVALUATION_OUTPUT),
], WORKING_ROOT / 'identity-evaluation.log', idle_seconds=900, total_seconds=7200)
run_bounded([
    str(PYTHON), str(RUNNER), 'verify',
    '--model-input', str(MODEL_INPUT), '--scoring', str(SCORING),
    '--output', str(EVALUATION_OUTPUT),
], WORKING_ROOT / 'identity-evaluation-validation.log', idle_seconds=300, total_seconds=600)

{"event": "scene_evaluated", "scene_number": 1, "total": 100}
{"event": "scene_evaluated", "scene_number": 2, "total": 100}
{"event": "scene_evaluated", "scene_number": 3, "total": 100}
{"event": "scene_evaluated", "scene_number": 4, "total": 100}
{"event": "scene_evaluated", "scene_number": 5, "total": 100}
{"event": "scene_evaluated", "scene_number": 6, "total": 100}
{"event": "scene_evaluated", "scene_number": 7, "total": 100}
{"event": "scene_evaluated", "scene_number": 8, "total": 100}
{"event": "scene_evaluated", "scene_number": 9, "total": 100}
{"event": "scene_evaluated", "scene_number": 10, "total": 100}
{"event": "scene_evaluated", "scene_number": 11, "total": 100}
{"event": "scene_evaluated", "scene_number": 12, "total": 100}
{"event": "scene_evaluated", "scene_number": 13, "total": 100}
{"event": "scene_evaluated", "scene_number": 14, "total": 100}
{"event": "scene_evaluated", "scene_number": 15, "total": 100}
{"event": "scene_evaluated", "scene_number": 16, "total": 100}
{"event": "scene_evaluated", "scene_number": 17, "total": 100}
{"event": "scene_evaluated", "scene_number": 18, "total": 100}
{"event": "scene_evaluated", "scene_number": 19, "total": 100}
{"event": "scene_evaluated", "scene_number": 20, "total": 100}
{"event": "scene_evaluated", "scene_number": 21, "total": 100}
{"event": "scene_evaluated", "scene_number": 22, "total": 100}
{"event": "scene_evaluated", "scene_number": 23, "total": 100}
{"event": "scene_evaluated", "scene_number": 24, "total": 100}
{"event": "scene_evaluated", "scene_number": 25, "total": 100}
{"event": "scene_evaluated", "scene_number": 26, "total": 100}
{"event": "scene_evaluated", "scene_number": 27, "total": 100}
{"event": "scene_evaluated", "scene_number": 28, "total": 100}
{"event": "scene_evaluated", "scene_number": 29, "total": 100}
{"event": "scene_evaluated", "scene_number": 30, "total": 100}
{"event": "scene_evaluated", "scene_number": 31, "total": 100}
{"event": "scene_evaluated", "scene_number": 32, "total": 100}
{"event": "scene_evaluated", "scene_number": 33, "total": 100}
{"event": "scene_evaluated", "scene_number": 34, "total": 100}
{"event": "scene_evaluated", "scene_number": 35, "total": 100}
{"event": "scene_evaluated", "scene_number": 36, "total": 100}
{"event": "scene_evaluated", "scene_number": 37, "total": 100}
{"event": "scene_evaluated", "scene_number": 38, "total": 100}
{"event": "scene_evaluated", "scene_number": 39, "total": 100}
{"event": "scene_evaluated", "scene_number": 40, "total": 100}
{"event": "scene_evaluated", "scene_number": 41, "total": 100}
{"event": "scene_evaluated", "scene_number": 42, "total": 100}
{"event": "scene_evaluated", "scene_number": 43, "total": 100}
{"event": "scene_evaluated", "scene_number": 44, "total": 100}
{"event": "scene_evaluated", "scene_number": 45, "total": 100}
{"event": "scene_evaluated", "scene_number": 46, "total": 100}
{"event": "scene_evaluated", "scene_number": 47, "total": 100}
{"event": "scene_evaluated", "scene_number": 48, "total": 100}
{"event": "scene_evaluated", "scene_number": 49, "total": 100}
{"event": "scene_evaluated", "scene_number": 50, "total": 100}
{"event": "scene_evaluated", "scene_number": 51, "total": 100}
{"event": "scene_evaluated", "scene_number": 52, "total": 100}
{"event": "scene_evaluated", "scene_number": 53, "total": 100}
{"event": "scene_evaluated", "scene_number": 54, "total": 100}
{"event": "scene_evaluated", "scene_number": 55, "total": 100}
{"event": "scene_evaluated", "scene_number": 56, "total": 100}
{"event": "scene_evaluated", "scene_number": 57, "total": 100}
{"event": "scene_evaluated", "scene_number": 58, "total": 100}
{"event": "scene_evaluated", "scene_number": 59, "total": 100}
{"event": "scene_evaluated", "scene_number": 60, "total": 100}
{"event": "scene_evaluated", "scene_number": 61, "total": 100}
{"event": "scene_evaluated", "scene_number": 62, "total": 100}
{"event": "scene_evaluated", "scene_number": 63, "total": 100}
{"event": "scene_evaluated", "scene_number": 64, "total": 100}
{"event": "scene_evaluated", "scene_number": 65, "total": 100}
{"event": "scene_evaluated", "scene_number": 66, "total": 100}
{"event": "scene_evaluated", "scene_number": 67, "total": 100}
{"event": "scene_evaluated", "scene_number": 68, "total": 100}
{"event": "scene_evaluated", "scene_number": 69, "total": 100}
{"event": "scene_evaluated", "scene_number": 70, "total": 100}
{"event": "scene_evaluated", "scene_number": 71, "total": 100}
{"event": "scene_evaluated", "scene_number": 72, "total": 100}
{"event": "scene_evaluated", "scene_number": 73, "total": 100}
{"event": "scene_evaluated", "scene_number": 74, "total": 100}
{"event": "scene_evaluated", "scene_number": 75, "total": 100}
{"event": "scene_evaluated", "scene_number": 76, "total": 100}
{"event": "scene_evaluated", "scene_number": 77, "total": 100}
{"event": "scene_evaluated", "scene_number": 78, "total": 100}
{"event": "scene_evaluated", "scene_number": 79, "total": 100}
{"event": "scene_evaluated", "scene_number": 80, "total": 100}
{"event": "scene_evaluated", "scene_number": 81, "total": 100}
{"event": "scene_evaluated", "scene_number": 82, "total": 100}
{"event": "scene_evaluated", "scene_number": 83, "total": 100}
{"event": "scene_evaluated", "scene_number": 84, "total": 100}
{"event": "scene_evaluated", "scene_number": 85, "total": 100}
{"event": "scene_evaluated", "scene_number": 86, "total": 100}
{"event": "scene_evaluated", "scene_number": 87, "total": 100}
{"event": "scene_evaluated", "scene_number": 88, "total": 100}
{"event": "scene_evaluated", "scene_number": 89, "total": 100}
{"event": "scene_evaluated", "scene_number": 90, "total": 100}
{"event": "scene_evaluated", "scene_number": 91, "total": 100}
{"event": "scene_evaluated", "scene_number": 92, "total": 100}
{"event": "scene_evaluated", "scene_number": 93, "total": 100}
{"event": "scene_evaluated", "scene_number": 94, "total": 100}
{"event": "scene_evaluated", "scene_number": 95, "total": 100}
{"event": "scene_evaluated", "scene_number": 96, "total": 100}
{"event": "scene_evaluated", "scene_number": 97, "total": 100}
{"event": "scene_evaluated", "scene_number": 98, "total": 100}
{"event": "scene_evaluated", "scene_number": 99, "total": 100}
{"event": "scene_evaluated", "scene_number": 100, "total": 100}
        configuration_id     descriptor  unmatched_cost  view_count           method  scenes  asset_groups       ap  top1  recall_at_2    auroc  identity_link_precision  identity_link_recall  identity_link_f1  identity_track_purity  winner_support  winner_purity
global_current__u020__v2 global_current            0.20           2       P1_current     100            27 0.429790  0.33        0.390 0.439851                 0.107833              0.059167          0.072437               0.920000            1.20       0.735000
global_current__u020__v2 global_current            0.20           2     P2_consensus     100            27 0.416143  0.31        0.390 0.425071                 0.107833              0.059167          0.072437               0.920000            1.21       0.685000
global_current__u020__v2 global_current            0.20           2 forward_02_cov70     100            27 0.460242  0.39        0.430 0.458291                 0.107833              0.059167          0.072437               0.920000            1.23       0.750000
global_current__u020__v2 global_current            0.20           2  forward_10_cov0     100            27 0.453444  0.36        0.410 0.453889                 0.107833              0.059167          0.072437               0.920000            1.22       0.750000
global_current__u020__v3 global_current            0.20           3       P1_current     100            27 0.345850  0.27        0.290 0.371109                 0.197740              0.095571          0.121122               0.858556            1.41       0.588333
global_current__u020__v3 global_current            0.20           3     P2_consensus     100            27 0.343286  0.26        0.315 0.373269                 0.197740              0.095571          0.121122               0.858556            1.34       0.543333
global_current__u020__v3 global_current            0.20           3 forward_02_cov70     100            27 0.374627  0.31        0.335 0.403671                 0.197740              0.095571          0.121122               0.858556            1.37       0.530000
global_current__u020__v3 global_current            0.20           3  forward_10_cov0     100            27 0.356220  0.29        0.290 0.382562                 0.197740              0.095571          0.121122               0.858556            1.36       0.560000
global_current__u020__v5 global_current            0.20           5       P1_current     100            27 0.214695  0.13        0.175 0.292029                 0.235475              0.117249          0.147329               0.763208            1.47       0.300667
global_current__u020__v5 global_current            0.20           5     P2_consensus     100            27 0.214021  0.13        0.170 0.288782                 0.235475              0.117249          0.147329               0.763208            1.53       0.283000
global_current__u020__v5 global_current            0.20           5 forward_02_cov70     100            27 0.256147  0.21        0.215 0.318836                 0.235475              0.117249          0.147329               0.763208            1.58       0.321167
global_current__u020__v5 global_current            0.20           5  forward_10_cov0     100            27 0.237421  0.17        0.180 0.309726                 0.235475              0.117249          0.147329               0.763208            1.50       0.324167
global_current__u035__v2 global_current            0.35           2       P1_current     100            27 0.324845  0.24        0.300 0.319875                 0.154667              0.136500          0.142444               0.740000            1.56       0.650000
global_current__u035__v2 global_current            0.35           2     P2_consensus     100            27 0.316679  0.22        0.310 0.308625                 0.154667              0.136500          0.142444               0.740000            1.64       0.590000
global_current__u035__v2 global_current            0.35           2 forward_02_cov70     100            27 0.335833  0.27        0.325 0.323417                 0.154667              0.136500          0.142444               0.740000            1.59       0.610000
global_current__u035__v2 global_current            0.35           2  forward_10_cov0     100            27 0.328429  0.23        0.350 0.321208                 0.154667              0.136500          0.142444               0.740000            1.56       0.635000
global_current__u035__v3 global_current            0.35           3       P1_current     100            27 0.319980  0.23        0.295 0.305462                 0.212644              0.173899          0.188789               0.687222            2.15       0.476667
global_current__u035__v3 global_current            0.35           3     P2_consensus     100            27 0.316694  0.21        0.290 0.313333                 0.212644              0.173899          0.188789               0.687222            2.15       0.455000
global_current__u035__v3 global_current            0.35           3 forward_02_cov70     100            27 0.339835  0.24        0.355 0.335573                 0.212644              0.173899          0.188789               0.687222            2.10       0.426667
global_current__u035__v3 global_current            0.35           3  forward_10_cov0     100            27 0.341649  0.23        0.325 0.347312                 0.212644              0.173899          0.188789               0.687222            2.18       0.475000
global_current__u035__v5 global_current            0.35           5       P1_current     100            27 0.275236  0.19        0.295 0.301190                 0.257156              0.216434          0.232629               0.555000            2.88       0.301833
global_current__u035__v5 global_current            0.35           5     P2_consensus     100            27 0.254242  0.15        0.270 0.274824                 0.257156              0.216434          0.232629               0.555000            2.94       0.299833
global_current__u035__v5 global_current            0.35           5 forward_02_cov70     100            27 0.265845  0.17        0.280 0.299342                 0.257156              0.216434          0.232629               0.555000            3.10       0.313333
global_current__u035__v5 global_current            0.35           5  forward_10_cov0     100            27 0.273242  0.18        0.265 0.305232                 0.257156              0.216434          0.232629               0.555000            2.90       0.307000
global_current__u050__v2 global_current            0.50           2       P1_current     100            27 0.260667  0.19        0.240 0.241250                 0.181500              0.181167          0.180770               0.620000            1.84       0.635000
global_current__u050__v2 global_current            0.50           2     P2_consensus     100            27 0.263167  0.19        0.275 0.247083                 0.181500              0.181167          0.180770               0.620000            1.83       0.620000
global_current__u050__v2 global_current            0.50           2 forward_02_cov70     100            27 0.279500  0.22        0.275 0.258250                 0.181500              0.181167          0.180770               0.620000            1.84       0.640000
global_current__u050__v2 global_current            0.50           2  forward_10_cov0     100            27 0.265833  0.20        0.255 0.246417                 0.181500              0.181167          0.180770               0.620000            1.80       0.625000
global_current__u050__v3 global_current            0.50           3       P1_current     100            27 0.332345  0.25        0.310 0.303464                 0.190754              0.184966          0.187458               0.617778            2.60       0.516667
global_current__u050__v3 global_current            0.50           3     P2_consensus     100            27 0.335024  0.25        0.305 0.312321                 0.190754              0.184966          0.187458               0.617778            2.55       0.535000
global_current__u050__v3 global_current            0.50           3 forward_02_cov70     100            27 0.343833  0.25        0.340 0.318280                 0.190754              0.184966          0.187458               0.617778            2.59       0.515000
global_current__u050__v3 global_current            0.50           3  forward_10_cov0     100            27 0.334750  0.23        0.320 0.315137                 0.190754              0.184966          0.187458               0.617778            2.61       0.506667
global_current__u050__v5 global_current            0.50           5       P1_current     100            27 0.305417  0.23        0.320 0.313667                 0.255907              0.247050          0.251045               0.490889            4.29       0.430500
global_current__u050__v5 global_current            0.50           5     P2_consensus     100            27 0.303333  0.23        0.340 0.309750                 0.255907              0.247050          0.251045               0.490889            4.23       0.434500
global_current__u050__v5 global_current            0.50           5 forward_02_cov70     100            27 0.313333  0.23        0.365 0.328000                 0.255907              0.247050          0.251045               0.490889            4.38       0.452000
global_current__u050__v5 global_current            0.50           5  forward_10_cov0     100            27 0.301250  0.24        0.315 0.310708                 0.255907              0.247050          0.251045               0.490889            4.29       0.435333
hybrid25_cov25__u020__v2 hybrid25_cov25            0.20           2       P1_current     100            27 0.415790  0.32        0.375 0.422530                 0.107833              0.064167          0.076889               0.910000            1.21       0.730000
hybrid25_cov25__u020__v2 hybrid25_cov25            0.20           2     P2_consensus     100            27 0.404476  0.30        0.375 0.413511                 0.107833              0.064167          0.076889               0.910000            1.24       0.685000
hybrid25_cov25__u020__v2 hybrid25_cov25            0.20           2 forward_02_cov70     100            27 0.444242  0.37        0.415 0.446720                 0.107833              0.064167          0.076889               0.910000            1.25       0.720000
hybrid25_cov25__u020__v2 hybrid25_cov25            0.20           2  forward_10_cov0     100            27 0.437444  0.34        0.395 0.439942                 0.107833              0.064167          0.076889               0.910000            1.23       0.735000
hybrid25_cov25__u020__v3 hybrid25_cov25            0.20           3       P1_current     100            27 0.347248  0.28        0.295 0.361344                 0.201177              0.099571          0.126531               0.835500            1.41       0.561667
hybrid25_cov25__u020__v3 hybrid25_cov25            0.20           3     P2_consensus     100            27 0.334639  0.25        0.300 0.367832                 0.201177              0.099571          0.126531               0.835500            1.35       0.486667
hybrid25_cov25__u020__v3 hybrid25_cov25            0.20           3 forward_02_cov70     100            27 0.365397  0.29        0.330 0.393058                 0.201177              0.099571          0.126531               0.835500            1.38       0.500000
hybrid25_cov25__u020__v3 hybrid25_cov25            0.20           3  forward_10_cov0     100            27 0.353673  0.29        0.290 0.382596                 0.201177              0.099571          0.126531               0.835500            1.36       0.550000
hybrid25_cov25__u020__v5 hybrid25_cov25            0.20           5       P1_current     100            27 0.251695  0.16        0.220 0.325242                 0.242367              0.123126          0.154301               0.788972            1.54       0.331667
hybrid25_cov25__u020__v5 hybrid25_cov25            0.20           5     P2_consensus     100            27 0.241288  0.14        0.190 0.332015                 0.242367              0.123126          0.154301               0.788972            1.57       0.295667
hybrid25_cov25__u020__v5 hybrid25_cov25            0.20           5 forward_02_cov70     100            27 0.282205  0.20        0.250 0.363744                 0.242367              0.123126          0.154301               0.788972            1.68       0.333500
hybrid25_cov25__u020__v5 hybrid25_cov25            0.20           5  forward_10_cov0     100            27 0.271230  0.19        0.210 0.343285                 0.242367              0.123126          0.154301               0.788972            1.56       0.341000
hybrid25_cov25__u035__v2 hybrid25_cov25            0.35           2       P1_current     100            27 0.317583  0.24        0.295 0.307708                 0.165000              0.147667          0.153302               0.750000            1.57       0.655000
hybrid25_cov25__u035__v2 hybrid25_cov25            0.35           2     P2_consensus     100            27 0.302845  0.21        0.295 0.291208                 0.165000              0.147667          0.153302               0.750000            1.66       0.590000
hybrid25_cov25__u035__v2 hybrid25_cov25            0.35           2 forward_02_cov70     100            27 0.329500  0.27        0.310 0.312917                 0.165000              0.147667          0.153302               0.750000            1.62       0.630000

## Summary tables

Start with the three-view automatic route and the directed patch scorer. Compare top-1 accuracy with identity link F1 and inspect the paired asset-group intervals. Do not select a method from top-1 alone.

In [7]:
import pandas as pd
for file_name in (
    'primary_candidate_ranking.csv',
    'identity_refinement_summary.csv',
    'paired_asset_intervals.csv',
    'patch_fallback_summary.csv',
    'category_summary.csv',
    'family_summary.csv',
):
    print(file_name)
    display(pd.read_csv(EVALUATION_OUTPUT / 'shareable' / file_name))
display(json.loads((EVALUATION_OUTPUT / 'shareable/development_decision.json').read_text()))

primary_candidate_ranking.csv

,configuration_id,descriptor,unmatched_cost,view_count,method,scenes,asset_groups,ap,top1,recall_at_2,auroc,identity_link_precision,identity_link_recall,identity_link_f1,identity_track_purity,winner_support,winner_purity
0,hybrid50_cov25__u020__v3,hybrid50_cov25,0.20,3,forward_02_cov70,100,27,0.375897,0.31,0.335,0.397954,0.205782,0.113974,0.139612,0.842944,1.44,0.490000
1,global_current__u020__v3,global_current,0.20,3,forward_02_cov70,100,27,0.374627,0.31,0.335,0.403671,0.197740,0.095571,0.121122,0.858556,1.37,0.530000
2,local_cov05__u050__v3,local_cov05,0.50,3,forward_02_cov70,100,27,0.370083,0.30,0.365,0.346250,0.209516,0.206483,0.207789,0.610278,2.69,0.526667
3,hybrid25_cov25__u020__v3,hybrid25_cov25,0.20,3,forward_02_cov70,100,27,0.365397,0.29,0.330,0.393058,0.201177,0.099571,0.126531,0.835500,1.38,0.500000
4,local_cov50__u050__v3,local_cov50,0.50,3,forward_02_cov70,100,27,0.357333,0.28,0.350,0.333155,0.211047,0.207880,0.209220,0.634167,2.67,0.521667
5,local_cov05__u020__v3,local_cov05,0.20,3,forward_02_cov70,100,27,0.351159,0.28,0.330,0.368426,0.205510,0.129021,0.152857,0.807500,1.52,0.458333
6,local_cov50__u035__v3,local_cov50,0.35,3,forward_02_cov70,100,27,0.348083,0.28,0.350,0.332613,0.202532,0.181369,0.190040,0.655278,2.32,0.486667
7,local_cov25__u050__v3,local_cov25,0.50,3,forward_02_cov70,100,27,0.355667,0.27,0.335,0.327321,0.206356,0.203189,0.204529,0.627778,2.67,0.508333
8,hybrid75_cov25__u020__v3,hybrid75_cov25,0.20,3,forward_02_cov70,100,27,0.353560,0.27,0.325,0.386191,0.199722,0.116406,0.140021,0.816111,1.47,0.441667
9,hybrid50_cov25__u050__v3,hybrid50_cov25,0.50,3,forward_02_cov70,100,27,0.347417,0.27,0.335,0.313405,0.200936,0.196094,0.198140,0.625000,2.61,0.518333
10,local_cov50__u020__v3,local_cov50,0.20,3,forward_02_cov70,100,27,0.340956,0.27,0.310,0.363021,0.213512,0.123649,0.149000,0.815000,1.48,0.446667
11,local_cov05__u035__v3,local_cov05,0.35,3,forward_02_cov70,100,27,0.339500,0.27,0.355,0.334030,0.203892,0.185020,0.192895,0.648333,2.32,0.481667
12,hybrid75_cov25__u050__v3,hybrid75_cov25,0.50,3,forward_02_cov70,100,27,0.344750,0.26,0.320,0.312696,0.204531,0.200673,0.202299,0.628889,2.67,0.510000
13,local_cov25__u035__v3,local_cov25,0.35,3,forward_02_cov70,100,27,0.337500,0.26,0.345,0.329363,0.206598,0.184615,0.193763,0.664167,2.34,0.495000
14,local_cov25__u020__v3,local_cov25,0.20,3,forward_02_cov70,100,27,0.334159,0.26,0.305,0.351251,0.215488,0.128982,0.154077,0.808889,1.48,0.445000
15,global_current__u050__v3,global_current,0.50,3,forward_02_cov70,100,27,0.343833,0.25,0.340,0.318280,0.190754,0.184966,0.187458,0.617778,2.59,0.515000
16,hybrid75_cov25__u035__v3,hybrid75_cov25,0.35,3,forward_02_cov70,100,27,0.336417,0.25,0.340,0.329071,0.208565,0.186024,0.195305,0.665556,2.30,0.471667
17,hybrid50_cov25__u035__v3,hybrid50_cov25,0.35,3,forward_02_cov70,100,27,0.331012,0.25,0.335,0.316940,0.199094,0.175603,0.185172,0.679444,2.22,0.446667
18,global_current__u035__v3,global_current,0.35,3,forward_02_cov70,100,27,0.339835,0.24,0.355,0.335573,0.212644,0.173899,0.188789,0.687222,2.10,0.426667
19,hybrid25_cov25__u050__v3,hybrid25_cov25,0.50,3,forward_02_cov70,100,27,0.323667,0.23,0.310,0.293196,0.188816,0.183974,0.186021,0.611667,2.60,0.501667
20,hybrid25_cov25__u035__v3,hybrid25_cov25,0.35,3,forward_02_cov70,100,27,0.315794,0.22,0.340,0.309065,0.204524,0.171519,0.184315,0.663056,2.19,0.426667

identity_refinement_summary.csv

,configuration_id,descriptor,unmatched_cost,view_count,method,scenes,asset_groups,ap,top1,recall_at_2,auroc,identity_link_precision,identity_link_recall,identity_link_f1,identity_track_purity,winner_support,winner_purity
0,global_current__u020__v2,global_current,0.2,2,P1_current,100,27,0.429790,0.33,0.390,0.439851,0.107833,0.059167,0.072437,0.920000,1.20,0.735000
1,global_current__u020__v2,global_current,0.2,2,P2_consensus,100,27,0.416143,0.31,0.390,0.425071,0.107833,0.059167,0.072437,0.920000,1.21,0.685000
2,global_current__u020__v2,global_current,0.2,2,forward_02_cov70,100,27,0.460242,0.39,0.430,0.458291,0.107833,0.059167,0.072437,0.920000,1.23,0.750000
3,global_current__u020__v2,global_current,0.2,2,forward_10_cov0,100,27,0.453444,0.36,0.410,0.453889,0.107833,0.059167,0.072437,0.920000,1.22,0.750000
4,global_current__u020__v3,global_current,0.2,3,P1_current,100,27,0.345850,0.27,0.290,0.371109,0.197740,0.095571,0.121122,0.858556,1.41,0.588333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,local_cov50__u050__v3,local_cov50,0.5,3,forward_10_cov0,100,27,0.339750,0.24,0.310,0.309054,0.211047,0.207880,0.209220,0.634167,2.70,0.516667
248,local_cov50__u050__v5,local_cov50,0.5,5,P1_current,100,27,0.296667,0.19,0.315,0.286333,0.248404,0.241268,0.244491,0.514972,4.35,0.421000
249,local_cov50__u050__v5,local_cov50,0.5,5,P2_consensus,100,27,0.292917,0.18,0.310,0.282878,0.248404,0.241268,0.244491,0.514972,4.32,0.403833
250,local_cov50__u050__v5,local_cov50,0.5,5,forward_02_cov70,100,27,0.343250,0.25,0.400,0.355000,0.248404,0.241268,0.244491,0.514972,4.38,0.429500
251,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,100,27,0.303750,0.20,0.320,0.305250,0.248404,0.241268,0.244491,0.514972,4.37,0.422000

paired_asset_intervals.csv

,view_count,method,measure,candidate,baseline,difference,ci_low,ci_high,asset_groups,scenes
0,2,P1_current,ap,global_current__u020__v2,global_current__u035__v2,0.104944,0.036477,0.172819,27,100
1,2,P1_current,ap,global_current__u050__v2,global_current__u035__v2,-0.064179,-0.110882,-0.021333,27,100
2,2,P1_current,ap,hybrid25_cov25__u020__v2,global_current__u035__v2,0.090944,0.026746,0.163500,27,100
3,2,P1_current,ap,hybrid25_cov25__u035__v2,global_current__u035__v2,-0.007262,-0.034014,0.013093,27,100
4,2,P1_current,ap,hybrid25_cov25__u050__v2,global_current__u035__v2,-0.095012,-0.152320,-0.043111,27,100
...,...,...,...,...,...,...,...,...,...,...
715,5,forward_10_cov0,identity_link_f1,local_cov25__u035__v5,global_current__u035__v5,0.000629,-0.014657,0.014919,27,100
716,5,forward_10_cov0,identity_link_f1,local_cov25__u050__v5,global_current__u035__v5,0.014877,-0.001466,0.030073,27,100
717,5,forward_10_cov0,identity_link_f1,local_cov50__u020__v5,global_current__u035__v5,-0.060442,-0.079555,-0.041390,27,100
718,5,forward_10_cov0,identity_link_f1,local_cov50__u035__v5,global_current__u035__v5,-0.000048,-0.016444,0.015140,27,100
719,5,forward_10_cov0,identity_link_f1,local_cov50__u050__v5,global_current__u035__v5,0.011862,-0.003239,0.027003,27,100

patch_fallback_summary.csv

        coverage  fallback_count
0  coverage_0.05               0
1  coverage_0.25               0
2  coverage_0.50               0

category_summary.csv

,configuration_id,descriptor,unmatched_cost,view_count,method,category,ap,top1,identity_link_f1
0,global_current__u020__v2,global_current,0.2,2,P1_current,apple,0.375000,0.250000,0.000000
1,global_current__u020__v2,global_current,0.2,2,P1_current,bottle,0.166667,0.000000,0.083333
2,global_current__u020__v2,global_current,0.2,2,P1_current,bowl,0.833333,0.666667,0.111111
3,global_current__u020__v2,global_current,0.2,2,P1_current,bread,0.431548,0.250000,0.000000
4,global_current__u020__v2,global_current,0.2,2,P1_current,bunny,0.166667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
6799,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,monkey,0.000000,0.000000,0.144841
6800,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,mouse,0.000000,0.000000,0.204074
6801,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,orange,0.333333,0.333333,0.188333
6802,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,pig,0.500000,0.333333,0.218333
6803,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,shark,0.083333,0.000000,0.187500

family_summary.csv

,configuration_id,descriptor,unmatched_cost,view_count,method,families,ap,top1,identity_link_f1
0,global_current__u020__v2,global_current,0.2,2,P1_current,bump,0.550866,0.454545,0.074459
1,global_current__u020__v2,global_current,0.2,2,P1_current,crack,0.425490,0.352941,0.043137
2,global_current__u020__v2,global_current,0.2,2,P1_current,crack+disc,0.541667,0.750000,0.000000
3,global_current__u020__v2,global_current,0.2,2,P1_current,crack+frac,0.495536,0.375000,0.091667
4,global_current__u020__v2,global_current,0.2,2,P1_current,defr,0.166667,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
2767,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,frac,0.473684,0.315789,0.269185
2768,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,miss,0.500000,0.375000,0.356944
2769,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,miss+tran,0.375000,0.500000,0.262500
2770,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,rota,0.000000,0.000000,0.162656
2771,local_cov50__u050__v5,local_cov50,0.5,5,forward_10_cov0,tran,0.250000,0.000000,0.224627

{'baseline': 'global_current__u035__v3',
 'development_candidate': 'hybrid50_cov25__u020__v3',
 'primary_route': 'automatic masks, predicted identity, three views',
 'primary_scorer': 'forward_02_cov70',
 'promotion': 'No automatic promotion. Review intervals, identity quality, subgroups and galleries.',
 'protected_data_used': False,
 'split_changed': False,
 'status': 'review_required'}

## Graphs and private gallery

The first graph ranks the strongest three-view candidates. The second checks whether an odd-one-out improvement is accompanied by better identity links. The private gallery contains fixed samples, improvements and regressions. Red marks the selected identity, green marks the reference unusual object and blue marks other automatic candidates. A red mask is shown only where the final automatic route produced an object mask.

In [8]:
from IPython.display import Image as NotebookImage, display
for figure in sorted((EVALUATION_OUTPUT / 'shareable/figures').glob('*.png')):
    print(figure.name)
    display(NotebookImage(filename=str(figure)))
gallery = json.loads((EVALUATION_OUTPUT / 'private/gallery_manifest.json').read_text())
for item in gallery['examples']:
    print(item['file'], ':', item['selection_reason'])
    display(NotebookImage(filename=str(EVALUATION_OUTPUT / 'private/figures' / item['file'])))

identity_vs_top1.png

primary_top1_comparison.png

identity_example_01.png : improvement

identity_example_02.png : improvement

identity_example_03.png : improvement

identity_example_04.png : improvement

identity_example_05.png : regression

identity_example_06.png : regression

identity_example_07.png : regression

identity_example_08.png : regression

identity_example_09.png : fixed_hash_sample

identity_example_10.png : fixed_hash_sample

identity_example_11.png : fixed_hash_sample

identity_example_12.png : fixed_hash_sample

## Experiment tracking

ClearML runs only after the scientific outputs are sealed. It receives aggregate tables, decision records, summary graphs, metrics and checksums. It does not receive private galleries, labels, per-scene rows, raw images or credentials. A tracking failure can be retried without rerunning DINO.

In [9]:
if tracking_credentials():
    try:
        subprocess.run([
            str(PYTHON), '-m', 'pip', 'install', '--retries', '1', '--timeout', '30',
            '--only-binary=:all:', '--upgrade', '--target', str(PACKAGE_ROOT),
            '-r', str(SOURCE / 'requirements/identity-refinement-tracking.txt'),
        ], check=True, timeout=180)
        subprocess.run([
            str(PYTHON), str(SOURCE / 'scripts/log_identity_refinement.py'),
            '--evidence', str(EVALUATION_OUTPUT),
        ], check=True, timeout=180)
    except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
        print('ClearML upload is not verified. Preserve the outputs and retry only the tracking command.')
else:
    print('ClearML secrets are unavailable. Preserve the outputs and enable the existing notebook secrets.')

ClearML secrets are unavailable. Preserve the outputs and enable the existing notebook secrets.

## Evidence export and review

Download the executed notebook, three log files, both complete output directories and the recovery archive with its manifest. Verify lock files after download. Keep private gallery images, per-scene metrics, model inputs and recovery data outside GitHub. A later repository package should contain the clean notebook, source, tests, safe tables, summary figures, sanitized executed notebook and verified run receipts.

Review successes and failures before freezing a method. If no local or hybrid descriptor improves both downstream ranking and identity quality, retain the current method and keep optional human correction after the automatic result.

In [10]:
print('Prediction evidence:', PREDICTION_OUTPUT)
print('Evaluation evidence:', EVALUATION_OUTPUT)
print('Recovery archive:', PREDICTION_OUTPUT.parent / f'{PREDICTION_OUTPUT.name}-recovery.zip')
print('The development decision remains pending manual review.')

Prediction evidence: /kaggle/working/identity-refinement-predictions
Evaluation evidence: /kaggle/working/identity-refinement-evaluation
Recovery archive: /kaggle/working/identity-refinement-predictions-recovery.zip
The development decision remains pending manual review.

## Working-directory cleanup

Remove only disposable dependency, extraction and plotting folders after outputs and optional tracking have finished. Prediction checkpoints, locks, logs, tables, graphs and galleries remain available for download.

In [11]:
for path in (
    PACKAGE_ROOT,
    WORKING_ROOT / 'matplotlib',
    WORKING_ROOT / 'identity-source',
    WORKING_ROOT / 'identity-model-resource',
    WORKING_ROOT / 'identity-evaluator-resource',
):
    if path.exists():
        shutil.rmtree(path)
print('Disposable directories removed. Scientific evidence is unchanged.')

Disposable directories removed. Scientific evidence is unchanged.